//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Requests
{
    using StackOne.Client.Utils;
    
    /// <summary>
    /// ATS Application Filter
    /// </summary>
    public class AtsListApplicationsFilter
    {

        /// <summary>
        /// Use a string with a date to only select results updated after that given date
        /// </summary>
        [SpeakeasyMetadata("queryParam:name=updated_after")]
        public string? UpdatedAfter { get; set; } = null;

        /// <summary>
        /// Use a string with a date to only select results created after that given date
        /// </summary>
        [SpeakeasyMetadata("queryParam:name=created_after")]
        public string? CreatedAfter { get; set; } = null;

        /// <summary>
        /// Filter to select applications by job_id
        /// </summary>
        [SpeakeasyMetadata("queryParam:name=job_id")]
        public string? JobId { get; set; } = null;

        /// <summary>
        /// Filter to select applications by stage and sub-stage
        /// </summary>
        [SpeakeasyMetadata("queryParam:name=stage")]
        public string? Stage { get; set; } = null;
    }
}