//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Requests
{
    using Newtonsoft.Json;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    
    public class HrisListEmployeeTimeOffRequestsResponse
    {
        public Func<Task<HrisListEmployeeTimeOffRequestsResponse?>>? Next {get;set;}

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// The time off requests related to the employee with the given identifier were retrieved.
        /// </summary>
        public TimeOffPaginated? TimeOffPaginated { get; set; }

        public Dictionary<string, List<string>> Headers { get; set; } = default!;
    }
}