//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Type of account
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class AccountTypeValue : IEquatable<AccountTypeValue>
    {
        public static readonly AccountTypeValue Asset = new AccountTypeValue("asset");
        public static readonly AccountTypeValue Liability = new AccountTypeValue("liability");
        public static readonly AccountTypeValue Equity = new AccountTypeValue("equity");
        public static readonly AccountTypeValue Revenue = new AccountTypeValue("revenue");
        public static readonly AccountTypeValue Expense = new AccountTypeValue("expense");
        public static readonly AccountTypeValue UnmappedValue = new AccountTypeValue("unmapped_value");

        private static readonly Dictionary <string, AccountTypeValue> _knownValues =
            new Dictionary <string, AccountTypeValue> ()
            {
                ["asset"] = Asset,
                ["liability"] = Liability,
                ["equity"] = Equity,
                ["revenue"] = Revenue,
                ["expense"] = Expense,
                ["unmapped_value"] = UnmappedValue
            };

        private static readonly ConcurrentDictionary<string, AccountTypeValue> _values =
            new ConcurrentDictionary<string, AccountTypeValue>(_knownValues);

        private AccountTypeValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static AccountTypeValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new AccountTypeValue(value));
        }

        public static implicit operator AccountTypeValue(string value) => Of(value);
        public static implicit operator string(AccountTypeValue accounttypevalue) => accounttypevalue.Value;

        public static AccountTypeValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as AccountTypeValue);

        public bool Equals(AccountTypeValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}