//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class AccountingJournalSourceValueUnionType
    {
        private AccountingJournalSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static AccountingJournalSourceValueUnionType Str { get { return new AccountingJournalSourceValueUnionType("str"); } }
        
        public static AccountingJournalSourceValueUnionType Number { get { return new AccountingJournalSourceValueUnionType("number"); } }
        
        public static AccountingJournalSourceValueUnionType Boolean { get { return new AccountingJournalSourceValueUnionType("boolean"); } }
        
        public static AccountingJournalSourceValueUnionType AccountingJournalSourceValue { get { return new AccountingJournalSourceValueUnionType("AccountingJournal_source_value"); } }
        
        public static AccountingJournalSourceValueUnionType ArrayOfAny { get { return new AccountingJournalSourceValueUnionType("arrayOfAny"); } }
        
        public static AccountingJournalSourceValueUnionType Null { get { return new AccountingJournalSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AccountingJournalSourceValueUnionType v) { return v.Value; }
        public static AccountingJournalSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "AccountingJournal_source_value": return AccountingJournalSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for AccountingJournalSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AccountingJournalSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(AccountingJournalSourceValueUnion.AccountingJournalSourceValueUnionConverter))]
    public class AccountingJournalSourceValueUnion {
        public AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AccountingJournalSourceValue? AccountingJournalSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public AccountingJournalSourceValueUnionType Type { get; set; }


        public static AccountingJournalSourceValueUnion CreateStr(string str) {
            AccountingJournalSourceValueUnionType typ = AccountingJournalSourceValueUnionType.Str;

            AccountingJournalSourceValueUnion res = new AccountingJournalSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static AccountingJournalSourceValueUnion CreateNumber(double number) {
            AccountingJournalSourceValueUnionType typ = AccountingJournalSourceValueUnionType.Number;

            AccountingJournalSourceValueUnion res = new AccountingJournalSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static AccountingJournalSourceValueUnion CreateBoolean(bool boolean) {
            AccountingJournalSourceValueUnionType typ = AccountingJournalSourceValueUnionType.Boolean;

            AccountingJournalSourceValueUnion res = new AccountingJournalSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static AccountingJournalSourceValueUnion CreateAccountingJournalSourceValue(AccountingJournalSourceValue accountingJournalSourceValue) {
            AccountingJournalSourceValueUnionType typ = AccountingJournalSourceValueUnionType.AccountingJournalSourceValue;

            AccountingJournalSourceValueUnion res = new AccountingJournalSourceValueUnion(typ);
            res.AccountingJournalSourceValue = accountingJournalSourceValue;
            return res;
        }

        public static AccountingJournalSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            AccountingJournalSourceValueUnionType typ = AccountingJournalSourceValueUnionType.ArrayOfAny;

            AccountingJournalSourceValueUnion res = new AccountingJournalSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static AccountingJournalSourceValueUnion CreateNull() {
            AccountingJournalSourceValueUnionType typ = AccountingJournalSourceValueUnionType.Null;
            return new AccountingJournalSourceValueUnion(typ);
        }

        public class AccountingJournalSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(AccountingJournalSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.AccountingJournalSourceValue)
                    {
                        AccountingJournalSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AccountingJournalSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AccountingJournalSourceValue), new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.AccountingJournalSourceValue), "AccountingJournalSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new AccountingJournalSourceValueUnion(AccountingJournalSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                AccountingJournalSourceValueUnion res = (AccountingJournalSourceValueUnion)value;
                if (AccountingJournalSourceValueUnionType.FromString(res.Type).Equals(AccountingJournalSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.AccountingJournalSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AccountingJournalSourceValue));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}