//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class AccountingAccountActiveUnionType
    {
        private AccountingAccountActiveUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static AccountingAccountActiveUnionType Boolean { get { return new AccountingAccountActiveUnionType("boolean"); } }

        public static AccountingAccountActiveUnionType AccountingAccountActiveEnum { get { return new AccountingAccountActiveUnionType("AccountingAccount_active_enum"); } }

        public static AccountingAccountActiveUnionType Null { get { return new AccountingAccountActiveUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AccountingAccountActiveUnionType v) { return v.Value; }
        public static AccountingAccountActiveUnionType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "AccountingAccount_active_enum": return AccountingAccountActiveEnum;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for AccountingAccountActiveUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AccountingAccountActiveUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Whether the account is active
    /// </summary>
    [JsonConverter(typeof(AccountingAccountActiveUnion.AccountingAccountActiveUnionConverter))]
    public class AccountingAccountActiveUnion
    {
        public AccountingAccountActiveUnion(AccountingAccountActiveUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AccountingAccountActiveEnum? AccountingAccountActiveEnum { get; set; }

        public AccountingAccountActiveUnionType Type { get; set; }
        public static AccountingAccountActiveUnion CreateBoolean(bool boolean)
        {
            AccountingAccountActiveUnionType typ = AccountingAccountActiveUnionType.Boolean;

            AccountingAccountActiveUnion res = new AccountingAccountActiveUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static AccountingAccountActiveUnion CreateAccountingAccountActiveEnum(AccountingAccountActiveEnum accountingAccountActiveEnum)
        {
            AccountingAccountActiveUnionType typ = AccountingAccountActiveUnionType.AccountingAccountActiveEnum;

            AccountingAccountActiveUnion res = new AccountingAccountActiveUnion(typ);
            res.AccountingAccountActiveEnum = accountingAccountActiveEnum;
            return res;
        }

        public static AccountingAccountActiveUnion CreateNull()
        {
            AccountingAccountActiveUnionType typ = AccountingAccountActiveUnionType.Null;
            return new AccountingAccountActiveUnion(typ);
        }

        public class AccountingAccountActiveUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(AccountingAccountActiveUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new AccountingAccountActiveUnion(AccountingAccountActiveUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new AccountingAccountActiveUnion(AccountingAccountActiveUnionType.AccountingAccountActiveEnum)
                    {
                        AccountingAccountActiveEnum = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AccountingAccountActiveEnum>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AccountingAccountActiveEnum), new AccountingAccountActiveUnion(AccountingAccountActiveUnionType.AccountingAccountActiveEnum), "AccountingAccountActiveEnum"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                AccountingAccountActiveUnion res = (AccountingAccountActiveUnion)value;
                if (AccountingAccountActiveUnionType.FromString(res.Type).Equals(AccountingAccountActiveUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.AccountingAccountActiveEnum != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AccountingAccountActiveEnum));
                    return;
                }
            }

        }

    }
}