//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The ISO 3166-1 alpha-2 code of the country.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class AccountAddressCountryValue : IEquatable<AccountAddressCountryValue>
    {
        public static readonly AccountAddressCountryValue Af = new AccountAddressCountryValue("AF");
        public static readonly AccountAddressCountryValue Al = new AccountAddressCountryValue("AL");
        public static readonly AccountAddressCountryValue Dz = new AccountAddressCountryValue("DZ");
        public static readonly AccountAddressCountryValue As = new AccountAddressCountryValue("AS");
        public static readonly AccountAddressCountryValue Ad = new AccountAddressCountryValue("AD");
        public static readonly AccountAddressCountryValue Ao = new AccountAddressCountryValue("AO");
        public static readonly AccountAddressCountryValue Ai = new AccountAddressCountryValue("AI");
        public static readonly AccountAddressCountryValue Aq = new AccountAddressCountryValue("AQ");
        public static readonly AccountAddressCountryValue Ag = new AccountAddressCountryValue("AG");
        public static readonly AccountAddressCountryValue Ar = new AccountAddressCountryValue("AR");
        public static readonly AccountAddressCountryValue Am = new AccountAddressCountryValue("AM");
        public static readonly AccountAddressCountryValue Aw = new AccountAddressCountryValue("AW");
        public static readonly AccountAddressCountryValue Au = new AccountAddressCountryValue("AU");
        public static readonly AccountAddressCountryValue At = new AccountAddressCountryValue("AT");
        public static readonly AccountAddressCountryValue Az = new AccountAddressCountryValue("AZ");
        public static readonly AccountAddressCountryValue Bs = new AccountAddressCountryValue("BS");
        public static readonly AccountAddressCountryValue Bh = new AccountAddressCountryValue("BH");
        public static readonly AccountAddressCountryValue Bd = new AccountAddressCountryValue("BD");
        public static readonly AccountAddressCountryValue Bb = new AccountAddressCountryValue("BB");
        public static readonly AccountAddressCountryValue By = new AccountAddressCountryValue("BY");
        public static readonly AccountAddressCountryValue Be = new AccountAddressCountryValue("BE");
        public static readonly AccountAddressCountryValue Bz = new AccountAddressCountryValue("BZ");
        public static readonly AccountAddressCountryValue Bj = new AccountAddressCountryValue("BJ");
        public static readonly AccountAddressCountryValue Bm = new AccountAddressCountryValue("BM");
        public static readonly AccountAddressCountryValue Bt = new AccountAddressCountryValue("BT");
        public static readonly AccountAddressCountryValue Bo = new AccountAddressCountryValue("BO");
        public static readonly AccountAddressCountryValue Bq = new AccountAddressCountryValue("BQ");
        public static readonly AccountAddressCountryValue Ba = new AccountAddressCountryValue("BA");
        public static readonly AccountAddressCountryValue Bw = new AccountAddressCountryValue("BW");
        public static readonly AccountAddressCountryValue Bv = new AccountAddressCountryValue("BV");
        public static readonly AccountAddressCountryValue Br = new AccountAddressCountryValue("BR");
        public static readonly AccountAddressCountryValue Io = new AccountAddressCountryValue("IO");
        public static readonly AccountAddressCountryValue Bn = new AccountAddressCountryValue("BN");
        public static readonly AccountAddressCountryValue Bg = new AccountAddressCountryValue("BG");
        public static readonly AccountAddressCountryValue Bf = new AccountAddressCountryValue("BF");
        public static readonly AccountAddressCountryValue Bi = new AccountAddressCountryValue("BI");
        public static readonly AccountAddressCountryValue Kh = new AccountAddressCountryValue("KH");
        public static readonly AccountAddressCountryValue Cm = new AccountAddressCountryValue("CM");
        public static readonly AccountAddressCountryValue Ca = new AccountAddressCountryValue("CA");
        public static readonly AccountAddressCountryValue Cv = new AccountAddressCountryValue("CV");
        public static readonly AccountAddressCountryValue Ky = new AccountAddressCountryValue("KY");
        public static readonly AccountAddressCountryValue Cf = new AccountAddressCountryValue("CF");
        public static readonly AccountAddressCountryValue Td = new AccountAddressCountryValue("TD");
        public static readonly AccountAddressCountryValue Cl = new AccountAddressCountryValue("CL");
        public static readonly AccountAddressCountryValue Cn = new AccountAddressCountryValue("CN");
        public static readonly AccountAddressCountryValue Cx = new AccountAddressCountryValue("CX");
        public static readonly AccountAddressCountryValue Cc = new AccountAddressCountryValue("CC");
        public static readonly AccountAddressCountryValue Co = new AccountAddressCountryValue("CO");
        public static readonly AccountAddressCountryValue Km = new AccountAddressCountryValue("KM");
        public static readonly AccountAddressCountryValue Cg = new AccountAddressCountryValue("CG");
        public static readonly AccountAddressCountryValue Cd = new AccountAddressCountryValue("CD");
        public static readonly AccountAddressCountryValue Ck = new AccountAddressCountryValue("CK");
        public static readonly AccountAddressCountryValue Cr = new AccountAddressCountryValue("CR");
        public static readonly AccountAddressCountryValue Hr = new AccountAddressCountryValue("HR");
        public static readonly AccountAddressCountryValue Cu = new AccountAddressCountryValue("CU");
        public static readonly AccountAddressCountryValue Cw = new AccountAddressCountryValue("CW");
        public static readonly AccountAddressCountryValue Cy = new AccountAddressCountryValue("CY");
        public static readonly AccountAddressCountryValue Cz = new AccountAddressCountryValue("CZ");
        public static readonly AccountAddressCountryValue Ci = new AccountAddressCountryValue("CI");
        public static readonly AccountAddressCountryValue Dk = new AccountAddressCountryValue("DK");
        public static readonly AccountAddressCountryValue Dj = new AccountAddressCountryValue("DJ");
        public static readonly AccountAddressCountryValue Dm = new AccountAddressCountryValue("DM");
        public static readonly AccountAddressCountryValue Do = new AccountAddressCountryValue("DO");
        public static readonly AccountAddressCountryValue Ec = new AccountAddressCountryValue("EC");
        public static readonly AccountAddressCountryValue Eg = new AccountAddressCountryValue("EG");
        public static readonly AccountAddressCountryValue Sv = new AccountAddressCountryValue("SV");
        public static readonly AccountAddressCountryValue Gq = new AccountAddressCountryValue("GQ");
        public static readonly AccountAddressCountryValue Er = new AccountAddressCountryValue("ER");
        public static readonly AccountAddressCountryValue Ee = new AccountAddressCountryValue("EE");
        public static readonly AccountAddressCountryValue Et = new AccountAddressCountryValue("ET");
        public static readonly AccountAddressCountryValue Fk = new AccountAddressCountryValue("FK");
        public static readonly AccountAddressCountryValue Fo = new AccountAddressCountryValue("FO");
        public static readonly AccountAddressCountryValue Fj = new AccountAddressCountryValue("FJ");
        public static readonly AccountAddressCountryValue Fi = new AccountAddressCountryValue("FI");
        public static readonly AccountAddressCountryValue Fr = new AccountAddressCountryValue("FR");
        public static readonly AccountAddressCountryValue Gf = new AccountAddressCountryValue("GF");
        public static readonly AccountAddressCountryValue Pf = new AccountAddressCountryValue("PF");
        public static readonly AccountAddressCountryValue Tf = new AccountAddressCountryValue("TF");
        public static readonly AccountAddressCountryValue Ga = new AccountAddressCountryValue("GA");
        public static readonly AccountAddressCountryValue Gm = new AccountAddressCountryValue("GM");
        public static readonly AccountAddressCountryValue Ge = new AccountAddressCountryValue("GE");
        public static readonly AccountAddressCountryValue De = new AccountAddressCountryValue("DE");
        public static readonly AccountAddressCountryValue Gh = new AccountAddressCountryValue("GH");
        public static readonly AccountAddressCountryValue Gi = new AccountAddressCountryValue("GI");
        public static readonly AccountAddressCountryValue Gr = new AccountAddressCountryValue("GR");
        public static readonly AccountAddressCountryValue Gl = new AccountAddressCountryValue("GL");
        public static readonly AccountAddressCountryValue Gd = new AccountAddressCountryValue("GD");
        public static readonly AccountAddressCountryValue Gp = new AccountAddressCountryValue("GP");
        public static readonly AccountAddressCountryValue Gu = new AccountAddressCountryValue("GU");
        public static readonly AccountAddressCountryValue Gt = new AccountAddressCountryValue("GT");
        public static readonly AccountAddressCountryValue Gg = new AccountAddressCountryValue("GG");
        public static readonly AccountAddressCountryValue Gn = new AccountAddressCountryValue("GN");
        public static readonly AccountAddressCountryValue Gw = new AccountAddressCountryValue("GW");
        public static readonly AccountAddressCountryValue Gy = new AccountAddressCountryValue("GY");
        public static readonly AccountAddressCountryValue Ht = new AccountAddressCountryValue("HT");
        public static readonly AccountAddressCountryValue Hm = new AccountAddressCountryValue("HM");
        public static readonly AccountAddressCountryValue Va = new AccountAddressCountryValue("VA");
        public static readonly AccountAddressCountryValue Hn = new AccountAddressCountryValue("HN");
        public static readonly AccountAddressCountryValue Hk = new AccountAddressCountryValue("HK");
        public static readonly AccountAddressCountryValue Hu = new AccountAddressCountryValue("HU");
        public static readonly AccountAddressCountryValue Is = new AccountAddressCountryValue("IS");
        public static readonly AccountAddressCountryValue In = new AccountAddressCountryValue("IN");
        public static readonly AccountAddressCountryValue Id = new AccountAddressCountryValue("ID");
        public static readonly AccountAddressCountryValue Ir = new AccountAddressCountryValue("IR");
        public static readonly AccountAddressCountryValue Iq = new AccountAddressCountryValue("IQ");
        public static readonly AccountAddressCountryValue Ie = new AccountAddressCountryValue("IE");
        public static readonly AccountAddressCountryValue Im = new AccountAddressCountryValue("IM");
        public static readonly AccountAddressCountryValue Il = new AccountAddressCountryValue("IL");
        public static readonly AccountAddressCountryValue It = new AccountAddressCountryValue("IT");
        public static readonly AccountAddressCountryValue Jm = new AccountAddressCountryValue("JM");
        public static readonly AccountAddressCountryValue Jp = new AccountAddressCountryValue("JP");
        public static readonly AccountAddressCountryValue Je = new AccountAddressCountryValue("JE");
        public static readonly AccountAddressCountryValue Jo = new AccountAddressCountryValue("JO");
        public static readonly AccountAddressCountryValue Kz = new AccountAddressCountryValue("KZ");
        public static readonly AccountAddressCountryValue Ke = new AccountAddressCountryValue("KE");
        public static readonly AccountAddressCountryValue Ki = new AccountAddressCountryValue("KI");
        public static readonly AccountAddressCountryValue Kp = new AccountAddressCountryValue("KP");
        public static readonly AccountAddressCountryValue Kr = new AccountAddressCountryValue("KR");
        public static readonly AccountAddressCountryValue Kw = new AccountAddressCountryValue("KW");
        public static readonly AccountAddressCountryValue Kg = new AccountAddressCountryValue("KG");
        public static readonly AccountAddressCountryValue La = new AccountAddressCountryValue("LA");
        public static readonly AccountAddressCountryValue Lv = new AccountAddressCountryValue("LV");
        public static readonly AccountAddressCountryValue Lb = new AccountAddressCountryValue("LB");
        public static readonly AccountAddressCountryValue Ls = new AccountAddressCountryValue("LS");
        public static readonly AccountAddressCountryValue Lr = new AccountAddressCountryValue("LR");
        public static readonly AccountAddressCountryValue Ly = new AccountAddressCountryValue("LY");
        public static readonly AccountAddressCountryValue Li = new AccountAddressCountryValue("LI");
        public static readonly AccountAddressCountryValue Lt = new AccountAddressCountryValue("LT");
        public static readonly AccountAddressCountryValue Lu = new AccountAddressCountryValue("LU");
        public static readonly AccountAddressCountryValue Mo = new AccountAddressCountryValue("MO");
        public static readonly AccountAddressCountryValue Mk = new AccountAddressCountryValue("MK");
        public static readonly AccountAddressCountryValue Mg = new AccountAddressCountryValue("MG");
        public static readonly AccountAddressCountryValue Mw = new AccountAddressCountryValue("MW");
        public static readonly AccountAddressCountryValue My = new AccountAddressCountryValue("MY");
        public static readonly AccountAddressCountryValue Mv = new AccountAddressCountryValue("MV");
        public static readonly AccountAddressCountryValue Ml = new AccountAddressCountryValue("ML");
        public static readonly AccountAddressCountryValue Mt = new AccountAddressCountryValue("MT");
        public static readonly AccountAddressCountryValue Mh = new AccountAddressCountryValue("MH");
        public static readonly AccountAddressCountryValue Mq = new AccountAddressCountryValue("MQ");
        public static readonly AccountAddressCountryValue Mr = new AccountAddressCountryValue("MR");
        public static readonly AccountAddressCountryValue Mu = new AccountAddressCountryValue("MU");
        public static readonly AccountAddressCountryValue Yt = new AccountAddressCountryValue("YT");
        public static readonly AccountAddressCountryValue Mx = new AccountAddressCountryValue("MX");
        public static readonly AccountAddressCountryValue Fm = new AccountAddressCountryValue("FM");
        public static readonly AccountAddressCountryValue Md = new AccountAddressCountryValue("MD");
        public static readonly AccountAddressCountryValue Mc = new AccountAddressCountryValue("MC");
        public static readonly AccountAddressCountryValue Mn = new AccountAddressCountryValue("MN");
        public static readonly AccountAddressCountryValue Me = new AccountAddressCountryValue("ME");
        public static readonly AccountAddressCountryValue Ms = new AccountAddressCountryValue("MS");
        public static readonly AccountAddressCountryValue Ma = new AccountAddressCountryValue("MA");
        public static readonly AccountAddressCountryValue Mz = new AccountAddressCountryValue("MZ");
        public static readonly AccountAddressCountryValue Mm = new AccountAddressCountryValue("MM");
        public static readonly AccountAddressCountryValue Na = new AccountAddressCountryValue("NA");
        public static readonly AccountAddressCountryValue Nr = new AccountAddressCountryValue("NR");
        public static readonly AccountAddressCountryValue Np = new AccountAddressCountryValue("NP");
        public static readonly AccountAddressCountryValue Nl = new AccountAddressCountryValue("NL");
        public static readonly AccountAddressCountryValue Nc = new AccountAddressCountryValue("NC");
        public static readonly AccountAddressCountryValue Nz = new AccountAddressCountryValue("NZ");
        public static readonly AccountAddressCountryValue Ni = new AccountAddressCountryValue("NI");
        public static readonly AccountAddressCountryValue Ne = new AccountAddressCountryValue("NE");
        public static readonly AccountAddressCountryValue Ng = new AccountAddressCountryValue("NG");
        public static readonly AccountAddressCountryValue Nu = new AccountAddressCountryValue("NU");
        public static readonly AccountAddressCountryValue Nf = new AccountAddressCountryValue("NF");
        public static readonly AccountAddressCountryValue Mp = new AccountAddressCountryValue("MP");
        public static readonly AccountAddressCountryValue No = new AccountAddressCountryValue("NO");
        public static readonly AccountAddressCountryValue Om = new AccountAddressCountryValue("OM");
        public static readonly AccountAddressCountryValue Pk = new AccountAddressCountryValue("PK");
        public static readonly AccountAddressCountryValue Pw = new AccountAddressCountryValue("PW");
        public static readonly AccountAddressCountryValue Ps = new AccountAddressCountryValue("PS");
        public static readonly AccountAddressCountryValue Pa = new AccountAddressCountryValue("PA");
        public static readonly AccountAddressCountryValue Pg = new AccountAddressCountryValue("PG");
        public static readonly AccountAddressCountryValue Py = new AccountAddressCountryValue("PY");
        public static readonly AccountAddressCountryValue Pe = new AccountAddressCountryValue("PE");
        public static readonly AccountAddressCountryValue Ph = new AccountAddressCountryValue("PH");
        public static readonly AccountAddressCountryValue Pn = new AccountAddressCountryValue("PN");
        public static readonly AccountAddressCountryValue Pl = new AccountAddressCountryValue("PL");
        public static readonly AccountAddressCountryValue Pt = new AccountAddressCountryValue("PT");
        public static readonly AccountAddressCountryValue Pr = new AccountAddressCountryValue("PR");
        public static readonly AccountAddressCountryValue Qa = new AccountAddressCountryValue("QA");
        public static readonly AccountAddressCountryValue Ro = new AccountAddressCountryValue("RO");
        public static readonly AccountAddressCountryValue Ru = new AccountAddressCountryValue("RU");
        public static readonly AccountAddressCountryValue Rw = new AccountAddressCountryValue("RW");
        public static readonly AccountAddressCountryValue Re = new AccountAddressCountryValue("RE");
        public static readonly AccountAddressCountryValue Bl = new AccountAddressCountryValue("BL");
        public static readonly AccountAddressCountryValue Sh = new AccountAddressCountryValue("SH");
        public static readonly AccountAddressCountryValue Kn = new AccountAddressCountryValue("KN");
        public static readonly AccountAddressCountryValue Lc = new AccountAddressCountryValue("LC");
        public static readonly AccountAddressCountryValue Mf = new AccountAddressCountryValue("MF");
        public static readonly AccountAddressCountryValue Pm = new AccountAddressCountryValue("PM");
        public static readonly AccountAddressCountryValue Vc = new AccountAddressCountryValue("VC");
        public static readonly AccountAddressCountryValue Ws = new AccountAddressCountryValue("WS");
        public static readonly AccountAddressCountryValue Sm = new AccountAddressCountryValue("SM");
        public static readonly AccountAddressCountryValue St = new AccountAddressCountryValue("ST");
        public static readonly AccountAddressCountryValue Sa = new AccountAddressCountryValue("SA");
        public static readonly AccountAddressCountryValue Sn = new AccountAddressCountryValue("SN");
        public static readonly AccountAddressCountryValue Rs = new AccountAddressCountryValue("RS");
        public static readonly AccountAddressCountryValue Sc = new AccountAddressCountryValue("SC");
        public static readonly AccountAddressCountryValue Sl = new AccountAddressCountryValue("SL");
        public static readonly AccountAddressCountryValue Sg = new AccountAddressCountryValue("SG");
        public static readonly AccountAddressCountryValue Sx = new AccountAddressCountryValue("SX");
        public static readonly AccountAddressCountryValue Sk = new AccountAddressCountryValue("SK");
        public static readonly AccountAddressCountryValue Si = new AccountAddressCountryValue("SI");
        public static readonly AccountAddressCountryValue Sb = new AccountAddressCountryValue("SB");
        public static readonly AccountAddressCountryValue So = new AccountAddressCountryValue("SO");
        public static readonly AccountAddressCountryValue Za = new AccountAddressCountryValue("ZA");
        public static readonly AccountAddressCountryValue Gs = new AccountAddressCountryValue("GS");
        public static readonly AccountAddressCountryValue Ss = new AccountAddressCountryValue("SS");
        public static readonly AccountAddressCountryValue Es = new AccountAddressCountryValue("ES");
        public static readonly AccountAddressCountryValue Lk = new AccountAddressCountryValue("LK");
        public static readonly AccountAddressCountryValue Sd = new AccountAddressCountryValue("SD");
        public static readonly AccountAddressCountryValue Sr = new AccountAddressCountryValue("SR");
        public static readonly AccountAddressCountryValue Sj = new AccountAddressCountryValue("SJ");
        public static readonly AccountAddressCountryValue Sz = new AccountAddressCountryValue("SZ");
        public static readonly AccountAddressCountryValue Se = new AccountAddressCountryValue("SE");
        public static readonly AccountAddressCountryValue Ch = new AccountAddressCountryValue("CH");
        public static readonly AccountAddressCountryValue Sy = new AccountAddressCountryValue("SY");
        public static readonly AccountAddressCountryValue Tw = new AccountAddressCountryValue("TW");
        public static readonly AccountAddressCountryValue Tj = new AccountAddressCountryValue("TJ");
        public static readonly AccountAddressCountryValue Tz = new AccountAddressCountryValue("TZ");
        public static readonly AccountAddressCountryValue Th = new AccountAddressCountryValue("TH");
        public static readonly AccountAddressCountryValue Tl = new AccountAddressCountryValue("TL");
        public static readonly AccountAddressCountryValue Tg = new AccountAddressCountryValue("TG");
        public static readonly AccountAddressCountryValue Tk = new AccountAddressCountryValue("TK");
        public static readonly AccountAddressCountryValue To = new AccountAddressCountryValue("TO");
        public static readonly AccountAddressCountryValue Tt = new AccountAddressCountryValue("TT");
        public static readonly AccountAddressCountryValue Tn = new AccountAddressCountryValue("TN");
        public static readonly AccountAddressCountryValue Tr = new AccountAddressCountryValue("TR");
        public static readonly AccountAddressCountryValue Tm = new AccountAddressCountryValue("TM");
        public static readonly AccountAddressCountryValue Tc = new AccountAddressCountryValue("TC");
        public static readonly AccountAddressCountryValue Tv = new AccountAddressCountryValue("TV");
        public static readonly AccountAddressCountryValue Ug = new AccountAddressCountryValue("UG");
        public static readonly AccountAddressCountryValue Ua = new AccountAddressCountryValue("UA");
        public static readonly AccountAddressCountryValue Ae = new AccountAddressCountryValue("AE");
        public static readonly AccountAddressCountryValue Gb = new AccountAddressCountryValue("GB");
        public static readonly AccountAddressCountryValue Us = new AccountAddressCountryValue("US");
        public static readonly AccountAddressCountryValue Um = new AccountAddressCountryValue("UM");
        public static readonly AccountAddressCountryValue Uy = new AccountAddressCountryValue("UY");
        public static readonly AccountAddressCountryValue Uz = new AccountAddressCountryValue("UZ");
        public static readonly AccountAddressCountryValue Vu = new AccountAddressCountryValue("VU");
        public static readonly AccountAddressCountryValue Ve = new AccountAddressCountryValue("VE");
        public static readonly AccountAddressCountryValue Vn = new AccountAddressCountryValue("VN");
        public static readonly AccountAddressCountryValue Vg = new AccountAddressCountryValue("VG");
        public static readonly AccountAddressCountryValue Vi = new AccountAddressCountryValue("VI");
        public static readonly AccountAddressCountryValue Wf = new AccountAddressCountryValue("WF");
        public static readonly AccountAddressCountryValue Eh = new AccountAddressCountryValue("EH");
        public static readonly AccountAddressCountryValue Ye = new AccountAddressCountryValue("YE");
        public static readonly AccountAddressCountryValue Zm = new AccountAddressCountryValue("ZM");
        public static readonly AccountAddressCountryValue Zw = new AccountAddressCountryValue("ZW");
        public static readonly AccountAddressCountryValue UnmappedValue = new AccountAddressCountryValue("unmapped_value");

        private static readonly Dictionary <string, AccountAddressCountryValue> _knownValues =
            new Dictionary <string, AccountAddressCountryValue> ()
            {
                ["AF"] = Af,
                ["AL"] = Al,
                ["DZ"] = Dz,
                ["AS"] = As,
                ["AD"] = Ad,
                ["AO"] = Ao,
                ["AI"] = Ai,
                ["AQ"] = Aq,
                ["AG"] = Ag,
                ["AR"] = Ar,
                ["AM"] = Am,
                ["AW"] = Aw,
                ["AU"] = Au,
                ["AT"] = At,
                ["AZ"] = Az,
                ["BS"] = Bs,
                ["BH"] = Bh,
                ["BD"] = Bd,
                ["BB"] = Bb,
                ["BY"] = By,
                ["BE"] = Be,
                ["BZ"] = Bz,
                ["BJ"] = Bj,
                ["BM"] = Bm,
                ["BT"] = Bt,
                ["BO"] = Bo,
                ["BQ"] = Bq,
                ["BA"] = Ba,
                ["BW"] = Bw,
                ["BV"] = Bv,
                ["BR"] = Br,
                ["IO"] = Io,
                ["BN"] = Bn,
                ["BG"] = Bg,
                ["BF"] = Bf,
                ["BI"] = Bi,
                ["KH"] = Kh,
                ["CM"] = Cm,
                ["CA"] = Ca,
                ["CV"] = Cv,
                ["KY"] = Ky,
                ["CF"] = Cf,
                ["TD"] = Td,
                ["CL"] = Cl,
                ["CN"] = Cn,
                ["CX"] = Cx,
                ["CC"] = Cc,
                ["CO"] = Co,
                ["KM"] = Km,
                ["CG"] = Cg,
                ["CD"] = Cd,
                ["CK"] = Ck,
                ["CR"] = Cr,
                ["HR"] = Hr,
                ["CU"] = Cu,
                ["CW"] = Cw,
                ["CY"] = Cy,
                ["CZ"] = Cz,
                ["CI"] = Ci,
                ["DK"] = Dk,
                ["DJ"] = Dj,
                ["DM"] = Dm,
                ["DO"] = Do,
                ["EC"] = Ec,
                ["EG"] = Eg,
                ["SV"] = Sv,
                ["GQ"] = Gq,
                ["ER"] = Er,
                ["EE"] = Ee,
                ["ET"] = Et,
                ["FK"] = Fk,
                ["FO"] = Fo,
                ["FJ"] = Fj,
                ["FI"] = Fi,
                ["FR"] = Fr,
                ["GF"] = Gf,
                ["PF"] = Pf,
                ["TF"] = Tf,
                ["GA"] = Ga,
                ["GM"] = Gm,
                ["GE"] = Ge,
                ["DE"] = De,
                ["GH"] = Gh,
                ["GI"] = Gi,
                ["GR"] = Gr,
                ["GL"] = Gl,
                ["GD"] = Gd,
                ["GP"] = Gp,
                ["GU"] = Gu,
                ["GT"] = Gt,
                ["GG"] = Gg,
                ["GN"] = Gn,
                ["GW"] = Gw,
                ["GY"] = Gy,
                ["HT"] = Ht,
                ["HM"] = Hm,
                ["VA"] = Va,
                ["HN"] = Hn,
                ["HK"] = Hk,
                ["HU"] = Hu,
                ["IS"] = Is,
                ["IN"] = In,
                ["ID"] = Id,
                ["IR"] = Ir,
                ["IQ"] = Iq,
                ["IE"] = Ie,
                ["IM"] = Im,
                ["IL"] = Il,
                ["IT"] = It,
                ["JM"] = Jm,
                ["JP"] = Jp,
                ["JE"] = Je,
                ["JO"] = Jo,
                ["KZ"] = Kz,
                ["KE"] = Ke,
                ["KI"] = Ki,
                ["KP"] = Kp,
                ["KR"] = Kr,
                ["KW"] = Kw,
                ["KG"] = Kg,
                ["LA"] = La,
                ["LV"] = Lv,
                ["LB"] = Lb,
                ["LS"] = Ls,
                ["LR"] = Lr,
                ["LY"] = Ly,
                ["LI"] = Li,
                ["LT"] = Lt,
                ["LU"] = Lu,
                ["MO"] = Mo,
                ["MK"] = Mk,
                ["MG"] = Mg,
                ["MW"] = Mw,
                ["MY"] = My,
                ["MV"] = Mv,
                ["ML"] = Ml,
                ["MT"] = Mt,
                ["MH"] = Mh,
                ["MQ"] = Mq,
                ["MR"] = Mr,
                ["MU"] = Mu,
                ["YT"] = Yt,
                ["MX"] = Mx,
                ["FM"] = Fm,
                ["MD"] = Md,
                ["MC"] = Mc,
                ["MN"] = Mn,
                ["ME"] = Me,
                ["MS"] = Ms,
                ["MA"] = Ma,
                ["MZ"] = Mz,
                ["MM"] = Mm,
                ["NA"] = Na,
                ["NR"] = Nr,
                ["NP"] = Np,
                ["NL"] = Nl,
                ["NC"] = Nc,
                ["NZ"] = Nz,
                ["NI"] = Ni,
                ["NE"] = Ne,
                ["NG"] = Ng,
                ["NU"] = Nu,
                ["NF"] = Nf,
                ["MP"] = Mp,
                ["NO"] = No,
                ["OM"] = Om,
                ["PK"] = Pk,
                ["PW"] = Pw,
                ["PS"] = Ps,
                ["PA"] = Pa,
                ["PG"] = Pg,
                ["PY"] = Py,
                ["PE"] = Pe,
                ["PH"] = Ph,
                ["PN"] = Pn,
                ["PL"] = Pl,
                ["PT"] = Pt,
                ["PR"] = Pr,
                ["QA"] = Qa,
                ["RO"] = Ro,
                ["RU"] = Ru,
                ["RW"] = Rw,
                ["RE"] = Re,
                ["BL"] = Bl,
                ["SH"] = Sh,
                ["KN"] = Kn,
                ["LC"] = Lc,
                ["MF"] = Mf,
                ["PM"] = Pm,
                ["VC"] = Vc,
                ["WS"] = Ws,
                ["SM"] = Sm,
                ["ST"] = St,
                ["SA"] = Sa,
                ["SN"] = Sn,
                ["RS"] = Rs,
                ["SC"] = Sc,
                ["SL"] = Sl,
                ["SG"] = Sg,
                ["SX"] = Sx,
                ["SK"] = Sk,
                ["SI"] = Si,
                ["SB"] = Sb,
                ["SO"] = So,
                ["ZA"] = Za,
                ["GS"] = Gs,
                ["SS"] = Ss,
                ["ES"] = Es,
                ["LK"] = Lk,
                ["SD"] = Sd,
                ["SR"] = Sr,
                ["SJ"] = Sj,
                ["SZ"] = Sz,
                ["SE"] = Se,
                ["CH"] = Ch,
                ["SY"] = Sy,
                ["TW"] = Tw,
                ["TJ"] = Tj,
                ["TZ"] = Tz,
                ["TH"] = Th,
                ["TL"] = Tl,
                ["TG"] = Tg,
                ["TK"] = Tk,
                ["TO"] = To,
                ["TT"] = Tt,
                ["TN"] = Tn,
                ["TR"] = Tr,
                ["TM"] = Tm,
                ["TC"] = Tc,
                ["TV"] = Tv,
                ["UG"] = Ug,
                ["UA"] = Ua,
                ["AE"] = Ae,
                ["GB"] = Gb,
                ["US"] = Us,
                ["UM"] = Um,
                ["UY"] = Uy,
                ["UZ"] = Uz,
                ["VU"] = Vu,
                ["VE"] = Ve,
                ["VN"] = Vn,
                ["VG"] = Vg,
                ["VI"] = Vi,
                ["WF"] = Wf,
                ["EH"] = Eh,
                ["YE"] = Ye,
                ["ZM"] = Zm,
                ["ZW"] = Zw,
                ["unmapped_value"] = UnmappedValue
            };

        private static readonly ConcurrentDictionary<string, AccountAddressCountryValue> _values =
            new ConcurrentDictionary<string, AccountAddressCountryValue>(_knownValues);

        private AccountAddressCountryValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static AccountAddressCountryValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new AccountAddressCountryValue(value));
        }

        public static implicit operator AccountAddressCountryValue(string value) => Of(value);
        public static implicit operator string(AccountAddressCountryValue accountaddresscountryvalue) => accountaddresscountryvalue.Value;

        public static AccountAddressCountryValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as AccountAddressCountryValue);

        public bool Equals(AccountAddressCountryValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}