//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    
    public class ActionsRpcResponse
    {

        /// <summary>
        /// Cursor for fetching the next page of results
        /// </summary>
        [JsonProperty("next")]
        public string? Next { get; set; } = null;

        /// <summary>
        /// The response data from the action RPC call
        /// </summary>
        [JsonProperty("data")]
        public Data? Data { get; set; } = null;
    }
}