//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The content type of the attachment.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ApplicationAttachmentValue : IEquatable<ApplicationAttachmentValue>
    {
        public static readonly ApplicationAttachmentValue Text = new ApplicationAttachmentValue("text");
        public static readonly ApplicationAttachmentValue Pdf = new ApplicationAttachmentValue("pdf");
        public static readonly ApplicationAttachmentValue Video = new ApplicationAttachmentValue("video");
        public static readonly ApplicationAttachmentValue Other = new ApplicationAttachmentValue("other");
        public static readonly ApplicationAttachmentValue UnmappedValue = new ApplicationAttachmentValue("unmapped_value");

        private static readonly Dictionary <string, ApplicationAttachmentValue> _knownValues =
            new Dictionary <string, ApplicationAttachmentValue> ()
            {
                ["text"] = Text,
                ["pdf"] = Pdf,
                ["video"] = Video,
                ["other"] = Other,
                ["unmapped_value"] = UnmappedValue
            };

        private static readonly ConcurrentDictionary<string, ApplicationAttachmentValue> _values =
            new ConcurrentDictionary<string, ApplicationAttachmentValue>(_knownValues);

        private ApplicationAttachmentValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ApplicationAttachmentValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ApplicationAttachmentValue(value));
        }

        public static implicit operator ApplicationAttachmentValue(string value) => Of(value);
        public static implicit operator string(ApplicationAttachmentValue applicationattachmentvalue) => applicationattachmentvalue.Value;

        public static ApplicationAttachmentValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ApplicationAttachmentValue);

        public bool Equals(ApplicationAttachmentValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}