//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class AtsCreateOfferRequestDtoSourceValueUnionType
    {
        private AtsCreateOfferRequestDtoSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static AtsCreateOfferRequestDtoSourceValueUnionType Str { get { return new AtsCreateOfferRequestDtoSourceValueUnionType("str"); } }
        
        public static AtsCreateOfferRequestDtoSourceValueUnionType Number { get { return new AtsCreateOfferRequestDtoSourceValueUnionType("number"); } }
        
        public static AtsCreateOfferRequestDtoSourceValueUnionType Boolean { get { return new AtsCreateOfferRequestDtoSourceValueUnionType("boolean"); } }
        
        public static AtsCreateOfferRequestDtoSourceValueUnionType AtsCreateOfferRequestDtoSourceValue { get { return new AtsCreateOfferRequestDtoSourceValueUnionType("AtsCreateOfferRequestDto_source_value"); } }
        
        public static AtsCreateOfferRequestDtoSourceValueUnionType ArrayOfAny { get { return new AtsCreateOfferRequestDtoSourceValueUnionType("arrayOfAny"); } }
        
        public static AtsCreateOfferRequestDtoSourceValueUnionType Null { get { return new AtsCreateOfferRequestDtoSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AtsCreateOfferRequestDtoSourceValueUnionType v) { return v.Value; }
        public static AtsCreateOfferRequestDtoSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "AtsCreateOfferRequestDto_source_value": return AtsCreateOfferRequestDtoSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for AtsCreateOfferRequestDtoSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AtsCreateOfferRequestDtoSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the offer status.
    /// </summary>
    [JsonConverter(typeof(AtsCreateOfferRequestDtoSourceValueUnion.AtsCreateOfferRequestDtoSourceValueUnionConverter))]
    public class AtsCreateOfferRequestDtoSourceValueUnion {
        public AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AtsCreateOfferRequestDtoSourceValue? AtsCreateOfferRequestDtoSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public AtsCreateOfferRequestDtoSourceValueUnionType Type { get; set; }


        public static AtsCreateOfferRequestDtoSourceValueUnion CreateStr(string str) {
            AtsCreateOfferRequestDtoSourceValueUnionType typ = AtsCreateOfferRequestDtoSourceValueUnionType.Str;

            AtsCreateOfferRequestDtoSourceValueUnion res = new AtsCreateOfferRequestDtoSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static AtsCreateOfferRequestDtoSourceValueUnion CreateNumber(double number) {
            AtsCreateOfferRequestDtoSourceValueUnionType typ = AtsCreateOfferRequestDtoSourceValueUnionType.Number;

            AtsCreateOfferRequestDtoSourceValueUnion res = new AtsCreateOfferRequestDtoSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static AtsCreateOfferRequestDtoSourceValueUnion CreateBoolean(bool boolean) {
            AtsCreateOfferRequestDtoSourceValueUnionType typ = AtsCreateOfferRequestDtoSourceValueUnionType.Boolean;

            AtsCreateOfferRequestDtoSourceValueUnion res = new AtsCreateOfferRequestDtoSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static AtsCreateOfferRequestDtoSourceValueUnion CreateAtsCreateOfferRequestDtoSourceValue(AtsCreateOfferRequestDtoSourceValue atsCreateOfferRequestDtoSourceValue) {
            AtsCreateOfferRequestDtoSourceValueUnionType typ = AtsCreateOfferRequestDtoSourceValueUnionType.AtsCreateOfferRequestDtoSourceValue;

            AtsCreateOfferRequestDtoSourceValueUnion res = new AtsCreateOfferRequestDtoSourceValueUnion(typ);
            res.AtsCreateOfferRequestDtoSourceValue = atsCreateOfferRequestDtoSourceValue;
            return res;
        }

        public static AtsCreateOfferRequestDtoSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            AtsCreateOfferRequestDtoSourceValueUnionType typ = AtsCreateOfferRequestDtoSourceValueUnionType.ArrayOfAny;

            AtsCreateOfferRequestDtoSourceValueUnion res = new AtsCreateOfferRequestDtoSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static AtsCreateOfferRequestDtoSourceValueUnion CreateNull() {
            AtsCreateOfferRequestDtoSourceValueUnionType typ = AtsCreateOfferRequestDtoSourceValueUnionType.Null;
            return new AtsCreateOfferRequestDtoSourceValueUnion(typ);
        }

        public class AtsCreateOfferRequestDtoSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(AtsCreateOfferRequestDtoSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.AtsCreateOfferRequestDtoSourceValue)
                    {
                        AtsCreateOfferRequestDtoSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AtsCreateOfferRequestDtoSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AtsCreateOfferRequestDtoSourceValue), new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.AtsCreateOfferRequestDtoSourceValue), "AtsCreateOfferRequestDtoSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new AtsCreateOfferRequestDtoSourceValueUnion(AtsCreateOfferRequestDtoSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                AtsCreateOfferRequestDtoSourceValueUnion res = (AtsCreateOfferRequestDtoSourceValueUnion)value;
                if (AtsCreateOfferRequestDtoSourceValueUnionType.FromString(res.Type).Equals(AtsCreateOfferRequestDtoSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.AtsCreateOfferRequestDtoSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AtsCreateOfferRequestDtoSourceValue));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}