//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System.Collections.Generic;
    
    public class AtsCreateCandidatesAssessmentsRequestDtoCandidate
    {

        /// <summary>
        /// Unique identifier
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Provider&apos;s unique identifier
        /// </summary>
        [JsonProperty("remote_id")]
        public string? RemoteId { get; set; } = null;

        /// <summary>
        /// Candidate first name
        /// </summary>
        [JsonProperty("first_name")]
        public string? FirstName { get; set; } = null;

        /// <summary>
        /// Candidate last name
        /// </summary>
        [JsonProperty("last_name")]
        public string? LastName { get; set; } = null;

        /// <summary>
        /// List of candidate emails
        /// </summary>
        [JsonProperty("emails")]
        public List<CandidateEmail>? Emails { get; set; } = null;

        /// <summary>
        /// Value to pass through to the provider
        /// </summary>
        [JsonProperty("passthrough")]
        public Dictionary<string, object>? Passthrough { get; set; } = null;

        /// <summary>
        /// Candidate profile url
        /// </summary>
        [JsonProperty("profile_url")]
        public string? ProfileUrl { get; set; } = null;
    }
}