//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class AtsDocumentApiModelTypeSourceValueUnionType
    {
        private AtsDocumentApiModelTypeSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static AtsDocumentApiModelTypeSourceValueUnionType Str { get { return new AtsDocumentApiModelTypeSourceValueUnionType("str"); } }

        public static AtsDocumentApiModelTypeSourceValueUnionType Number { get { return new AtsDocumentApiModelTypeSourceValueUnionType("number"); } }

        public static AtsDocumentApiModelTypeSourceValueUnionType Boolean { get { return new AtsDocumentApiModelTypeSourceValueUnionType("boolean"); } }

        public static AtsDocumentApiModelTypeSourceValueUnionType AtsDocumentApiModelSourceValueType { get { return new AtsDocumentApiModelTypeSourceValueUnionType("AtsDocumentApiModel_source_value_type"); } }

        public static AtsDocumentApiModelTypeSourceValueUnionType ArrayOfAny { get { return new AtsDocumentApiModelTypeSourceValueUnionType("arrayOfAny"); } }

        public static AtsDocumentApiModelTypeSourceValueUnionType Null { get { return new AtsDocumentApiModelTypeSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AtsDocumentApiModelTypeSourceValueUnionType v) { return v.Value; }
        public static AtsDocumentApiModelTypeSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "AtsDocumentApiModel_source_value_type": return AtsDocumentApiModelSourceValueType;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for AtsDocumentApiModelTypeSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AtsDocumentApiModelTypeSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(AtsDocumentApiModelTypeSourceValueUnion.AtsDocumentApiModelTypeSourceValueUnionConverter))]
    public class AtsDocumentApiModelTypeSourceValueUnion
    {
        public AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AtsDocumentApiModelSourceValueType? AtsDocumentApiModelSourceValueType { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public AtsDocumentApiModelTypeSourceValueUnionType Type { get; set; }
        public static AtsDocumentApiModelTypeSourceValueUnion CreateStr(string str)
        {
            AtsDocumentApiModelTypeSourceValueUnionType typ = AtsDocumentApiModelTypeSourceValueUnionType.Str;

            AtsDocumentApiModelTypeSourceValueUnion res = new AtsDocumentApiModelTypeSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static AtsDocumentApiModelTypeSourceValueUnion CreateNumber(double number)
        {
            AtsDocumentApiModelTypeSourceValueUnionType typ = AtsDocumentApiModelTypeSourceValueUnionType.Number;

            AtsDocumentApiModelTypeSourceValueUnion res = new AtsDocumentApiModelTypeSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static AtsDocumentApiModelTypeSourceValueUnion CreateBoolean(bool boolean)
        {
            AtsDocumentApiModelTypeSourceValueUnionType typ = AtsDocumentApiModelTypeSourceValueUnionType.Boolean;

            AtsDocumentApiModelTypeSourceValueUnion res = new AtsDocumentApiModelTypeSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static AtsDocumentApiModelTypeSourceValueUnion CreateAtsDocumentApiModelSourceValueType(AtsDocumentApiModelSourceValueType atsDocumentAPIModelSourceValueType)
        {
            AtsDocumentApiModelTypeSourceValueUnionType typ = AtsDocumentApiModelTypeSourceValueUnionType.AtsDocumentApiModelSourceValueType;

            AtsDocumentApiModelTypeSourceValueUnion res = new AtsDocumentApiModelTypeSourceValueUnion(typ);
            res.AtsDocumentApiModelSourceValueType = atsDocumentAPIModelSourceValueType;
            return res;
        }
        public static AtsDocumentApiModelTypeSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            AtsDocumentApiModelTypeSourceValueUnionType typ = AtsDocumentApiModelTypeSourceValueUnionType.ArrayOfAny;

            AtsDocumentApiModelTypeSourceValueUnion res = new AtsDocumentApiModelTypeSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static AtsDocumentApiModelTypeSourceValueUnion CreateNull()
        {
            AtsDocumentApiModelTypeSourceValueUnionType typ = AtsDocumentApiModelTypeSourceValueUnionType.Null;
            return new AtsDocumentApiModelTypeSourceValueUnion(typ);
        }

        public class AtsDocumentApiModelTypeSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(AtsDocumentApiModelTypeSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.AtsDocumentApiModelSourceValueType)
                    {
                        AtsDocumentApiModelSourceValueType = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AtsDocumentApiModelSourceValueType>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AtsDocumentApiModelSourceValueType), new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.AtsDocumentApiModelSourceValueType), "AtsDocumentApiModelSourceValueType"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new AtsDocumentApiModelTypeSourceValueUnion(AtsDocumentApiModelTypeSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                AtsDocumentApiModelTypeSourceValueUnion res = (AtsDocumentApiModelTypeSourceValueUnion)value;
                if (AtsDocumentApiModelTypeSourceValueUnionType.FromString(res.Type).Equals(AtsDocumentApiModelTypeSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.AtsDocumentApiModelSourceValueType != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AtsDocumentApiModelSourceValueType));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}