//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class AttachmentSourceValueUnionType
    {
        private AttachmentSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static AttachmentSourceValueUnionType Str { get { return new AttachmentSourceValueUnionType("str"); } }

        public static AttachmentSourceValueUnionType Number { get { return new AttachmentSourceValueUnionType("number"); } }

        public static AttachmentSourceValueUnionType Boolean { get { return new AttachmentSourceValueUnionType("boolean"); } }

        public static AttachmentSourceValueUnionType AttachmentSourceValue { get { return new AttachmentSourceValueUnionType("Attachment_source_value"); } }

        public static AttachmentSourceValueUnionType ArrayOfAny { get { return new AttachmentSourceValueUnionType("arrayOfAny"); } }

        public static AttachmentSourceValueUnionType Null { get { return new AttachmentSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AttachmentSourceValueUnionType v) { return v.Value; }
        public static AttachmentSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "Attachment_source_value": return AttachmentSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for AttachmentSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AttachmentSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the content type.
    /// </summary>
    [JsonConverter(typeof(AttachmentSourceValueUnion.AttachmentSourceValueUnionConverter))]
    public class AttachmentSourceValueUnion
    {
        public AttachmentSourceValueUnion(AttachmentSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AttachmentSourceValue? AttachmentSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public AttachmentSourceValueUnionType Type { get; set; }
        public static AttachmentSourceValueUnion CreateStr(string str)
        {
            AttachmentSourceValueUnionType typ = AttachmentSourceValueUnionType.Str;

            AttachmentSourceValueUnion res = new AttachmentSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static AttachmentSourceValueUnion CreateNumber(double number)
        {
            AttachmentSourceValueUnionType typ = AttachmentSourceValueUnionType.Number;

            AttachmentSourceValueUnion res = new AttachmentSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static AttachmentSourceValueUnion CreateBoolean(bool boolean)
        {
            AttachmentSourceValueUnionType typ = AttachmentSourceValueUnionType.Boolean;

            AttachmentSourceValueUnion res = new AttachmentSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static AttachmentSourceValueUnion CreateAttachmentSourceValue(AttachmentSourceValue attachmentSourceValue)
        {
            AttachmentSourceValueUnionType typ = AttachmentSourceValueUnionType.AttachmentSourceValue;

            AttachmentSourceValueUnion res = new AttachmentSourceValueUnion(typ);
            res.AttachmentSourceValue = attachmentSourceValue;
            return res;
        }
        public static AttachmentSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            AttachmentSourceValueUnionType typ = AttachmentSourceValueUnionType.ArrayOfAny;

            AttachmentSourceValueUnion res = new AttachmentSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static AttachmentSourceValueUnion CreateNull()
        {
            AttachmentSourceValueUnionType typ = AttachmentSourceValueUnionType.Null;
            return new AttachmentSourceValueUnion(typ);
        }

        public class AttachmentSourceValueUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(AttachmentSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.AttachmentSourceValue)
                    {
                        AttachmentSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AttachmentSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AttachmentSourceValue), new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.AttachmentSourceValue), "AttachmentSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new AttachmentSourceValueUnion(AttachmentSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                AttachmentSourceValueUnion res = (AttachmentSourceValueUnion)value;
                if (AttachmentSourceValueUnionType.FromString(res.Type).Equals(AttachmentSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.AttachmentSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AttachmentSourceValue));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}