//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ClearingCodeSourceValueUnionType
    {
        private ClearingCodeSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static ClearingCodeSourceValueUnionType Str { get { return new ClearingCodeSourceValueUnionType("str"); } }

        public static ClearingCodeSourceValueUnionType Number { get { return new ClearingCodeSourceValueUnionType("number"); } }

        public static ClearingCodeSourceValueUnionType Boolean { get { return new ClearingCodeSourceValueUnionType("boolean"); } }

        public static ClearingCodeSourceValueUnionType ClearingCodeSourceValue { get { return new ClearingCodeSourceValueUnionType("ClearingCode_source_value"); } }

        public static ClearingCodeSourceValueUnionType ArrayOfAny { get { return new ClearingCodeSourceValueUnionType("arrayOfAny"); } }

        public static ClearingCodeSourceValueUnionType Null { get { return new ClearingCodeSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ClearingCodeSourceValueUnionType v) { return v.Value; }
        public static ClearingCodeSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "ClearingCode_source_value": return ClearingCodeSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ClearingCodeSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ClearingCodeSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(ClearingCodeSourceValueUnion.ClearingCodeSourceValueUnionConverter))]
    public class ClearingCodeSourceValueUnion
    {
        public ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ClearingCodeSourceValue? ClearingCodeSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public ClearingCodeSourceValueUnionType Type { get; set; }
        public static ClearingCodeSourceValueUnion CreateStr(string str)
        {
            ClearingCodeSourceValueUnionType typ = ClearingCodeSourceValueUnionType.Str;

            ClearingCodeSourceValueUnion res = new ClearingCodeSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static ClearingCodeSourceValueUnion CreateNumber(double number)
        {
            ClearingCodeSourceValueUnionType typ = ClearingCodeSourceValueUnionType.Number;

            ClearingCodeSourceValueUnion res = new ClearingCodeSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static ClearingCodeSourceValueUnion CreateBoolean(bool boolean)
        {
            ClearingCodeSourceValueUnionType typ = ClearingCodeSourceValueUnionType.Boolean;

            ClearingCodeSourceValueUnion res = new ClearingCodeSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static ClearingCodeSourceValueUnion CreateClearingCodeSourceValue(ClearingCodeSourceValue clearingCodeSourceValue)
        {
            ClearingCodeSourceValueUnionType typ = ClearingCodeSourceValueUnionType.ClearingCodeSourceValue;

            ClearingCodeSourceValueUnion res = new ClearingCodeSourceValueUnion(typ);
            res.ClearingCodeSourceValue = clearingCodeSourceValue;
            return res;
        }
        public static ClearingCodeSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            ClearingCodeSourceValueUnionType typ = ClearingCodeSourceValueUnionType.ArrayOfAny;

            ClearingCodeSourceValueUnion res = new ClearingCodeSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static ClearingCodeSourceValueUnion CreateNull()
        {
            ClearingCodeSourceValueUnionType typ = ClearingCodeSourceValueUnionType.Null;
            return new ClearingCodeSourceValueUnion(typ);
        }

        public class ClearingCodeSourceValueUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ClearingCodeSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.ClearingCodeSourceValue)
                    {
                        ClearingCodeSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ClearingCodeSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ClearingCodeSourceValue), new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.ClearingCodeSourceValue), "ClearingCodeSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new ClearingCodeSourceValueUnion(ClearingCodeSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                ClearingCodeSourceValueUnion res = (ClearingCodeSourceValueUnion)value;
                if (ClearingCodeSourceValueUnionType.FromString(res.Type).Equals(ClearingCodeSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.ClearingCodeSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ClearingCodeSourceValue));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}