//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ConnectSessionTokenAuthLinkOrganizationIdType
    {
        private ConnectSessionTokenAuthLinkOrganizationIdType(string value) { Value = value; }

        public string Value { get; private set; }

        public static ConnectSessionTokenAuthLinkOrganizationIdType Str { get { return new ConnectSessionTokenAuthLinkOrganizationIdType("str"); } }

        public static ConnectSessionTokenAuthLinkOrganizationIdType Integer { get { return new ConnectSessionTokenAuthLinkOrganizationIdType("integer"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ConnectSessionTokenAuthLinkOrganizationIdType v) { return v.Value; }
        public static ConnectSessionTokenAuthLinkOrganizationIdType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "integer": return Integer;
                default: throw new ArgumentException("Invalid value for ConnectSessionTokenAuthLinkOrganizationIdType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ConnectSessionTokenAuthLinkOrganizationIdType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ConnectSessionTokenAuthLinkOrganizationId.ConnectSessionTokenAuthLinkOrganizationIdConverter))]
    public class ConnectSessionTokenAuthLinkOrganizationId
    {
        public ConnectSessionTokenAuthLinkOrganizationId(ConnectSessionTokenAuthLinkOrganizationIdType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public long? Integer { get; set; }

        public ConnectSessionTokenAuthLinkOrganizationIdType Type { get; set; }
        public static ConnectSessionTokenAuthLinkOrganizationId CreateStr(string str)
        {
            ConnectSessionTokenAuthLinkOrganizationIdType typ = ConnectSessionTokenAuthLinkOrganizationIdType.Str;

            ConnectSessionTokenAuthLinkOrganizationId res = new ConnectSessionTokenAuthLinkOrganizationId(typ);
            res.Str = str;
            return res;
        }
        public static ConnectSessionTokenAuthLinkOrganizationId CreateInteger(long integer)
        {
            ConnectSessionTokenAuthLinkOrganizationIdType typ = ConnectSessionTokenAuthLinkOrganizationIdType.Integer;

            ConnectSessionTokenAuthLinkOrganizationId res = new ConnectSessionTokenAuthLinkOrganizationId(typ);
            res.Integer = integer;
            return res;
        }

        public class ConnectSessionTokenAuthLinkOrganizationIdConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ConnectSessionTokenAuthLinkOrganizationId);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new ConnectSessionTokenAuthLinkOrganizationId(ConnectSessionTokenAuthLinkOrganizationIdType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToInt64(json);
                    return new ConnectSessionTokenAuthLinkOrganizationId(ConnectSessionTokenAuthLinkOrganizationIdType.Integer)
                    {
                        Integer = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ConnectSessionTokenAuthLinkOrganizationId res = (ConnectSessionTokenAuthLinkOrganizationId)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Integer != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Integer));
                    return;
                }
            }

        }

    }
}