//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class ContractTypeSourceValueUnionType
    {
        private ContractTypeSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ContractTypeSourceValueUnionType Str { get { return new ContractTypeSourceValueUnionType("str"); } }
        
        public static ContractTypeSourceValueUnionType Number { get { return new ContractTypeSourceValueUnionType("number"); } }
        
        public static ContractTypeSourceValueUnionType Boolean { get { return new ContractTypeSourceValueUnionType("boolean"); } }
        
        public static ContractTypeSourceValueUnionType SourceValueContractType { get { return new ContractTypeSourceValueUnionType("source_value_contract_type"); } }
        
        public static ContractTypeSourceValueUnionType ArrayOfAny { get { return new ContractTypeSourceValueUnionType("arrayOfAny"); } }
        
        public static ContractTypeSourceValueUnionType Null { get { return new ContractTypeSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ContractTypeSourceValueUnionType v) { return v.Value; }
        public static ContractTypeSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "source_value_contract_type": return SourceValueContractType;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ContractTypeSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ContractTypeSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(ContractTypeSourceValueUnion.ContractTypeSourceValueUnionConverter))]
    public class ContractTypeSourceValueUnion {
        public ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public SourceValueContractType? SourceValueContractType { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public ContractTypeSourceValueUnionType Type { get; set; }


        public static ContractTypeSourceValueUnion CreateStr(string str) {
            ContractTypeSourceValueUnionType typ = ContractTypeSourceValueUnionType.Str;

            ContractTypeSourceValueUnion res = new ContractTypeSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static ContractTypeSourceValueUnion CreateNumber(double number) {
            ContractTypeSourceValueUnionType typ = ContractTypeSourceValueUnionType.Number;

            ContractTypeSourceValueUnion res = new ContractTypeSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static ContractTypeSourceValueUnion CreateBoolean(bool boolean) {
            ContractTypeSourceValueUnionType typ = ContractTypeSourceValueUnionType.Boolean;

            ContractTypeSourceValueUnion res = new ContractTypeSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static ContractTypeSourceValueUnion CreateSourceValueContractType(SourceValueContractType sourceValueContractType) {
            ContractTypeSourceValueUnionType typ = ContractTypeSourceValueUnionType.SourceValueContractType;

            ContractTypeSourceValueUnion res = new ContractTypeSourceValueUnion(typ);
            res.SourceValueContractType = sourceValueContractType;
            return res;
        }

        public static ContractTypeSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            ContractTypeSourceValueUnionType typ = ContractTypeSourceValueUnionType.ArrayOfAny;

            ContractTypeSourceValueUnion res = new ContractTypeSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static ContractTypeSourceValueUnion CreateNull() {
            ContractTypeSourceValueUnionType typ = ContractTypeSourceValueUnionType.Null;
            return new ContractTypeSourceValueUnion(typ);
        }

        public class ContractTypeSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ContractTypeSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.SourceValueContractType)
                    {
                        SourceValueContractType = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SourceValueContractType>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SourceValueContractType), new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.SourceValueContractType), "SourceValueContractType"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new ContractTypeSourceValueUnion(ContractTypeSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ContractTypeSourceValueUnion res = (ContractTypeSourceValueUnion)value;
                if (ContractTypeSourceValueUnionType.FromString(res.Type).Equals(ContractTypeSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.SourceValueContractType != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SourceValueContractType));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}