//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    
    public class Course
    {

        /// <summary>
        /// Unique identifier
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Provider&apos;s unique identifier
        /// </summary>
        [JsonProperty("remote_id")]
        public string? RemoteId { get; set; } = null;

        /// <summary>
        /// Custom Unified Fields configured in your StackOne project
        /// </summary>
        [JsonProperty("unified_custom_fields")]
        public Dictionary<string, object>? UnifiedCustomFields { get; set; } = null;

        /// <summary>
        /// The external ID associated with this course
        /// </summary>
        [JsonProperty("external_reference")]
        public string? ExternalReference { get; set; } = null;

        /// <summary>
        /// The child ID/IDs associated with this course
        /// </summary>
        [JsonProperty("content_ids")]
        public List<string>? ContentIds { get; set; } = null;

        /// <summary>
        /// Provider&apos;s unique identifier of the child content IDs associated with this course
        /// </summary>
        [JsonProperty("remote_content_ids")]
        public List<string>? RemoteContentIds { get; set; } = null;

        /// <summary>
        /// The title of the course
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The description of the course
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// The languages associated with this course
        /// </summary>
        [JsonProperty("languages")]
        public List<LanguageEnum>? Languages { get; set; } = null;

        /// <summary>
        /// The URL of the thumbnail image associated with the course.
        /// </summary>
        [JsonProperty("cover_url")]
        public string? CoverUrl { get; set; } = null;

        /// <summary>
        /// The redirect URL of the course.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; } = null;

        /// <summary>
        /// Whether the course is active and available for users.
        /// </summary>
        [JsonProperty("active", NullValueHandling = NullValueHandling.Include)]
        public CourseActiveUnion? Active { get; set; } = null;

        /// <summary>
        /// The duration of the course following the ISO8601 standard. If duration_unit is applicable we will derive this from the smallest unit given in the duration string
        /// </summary>
        [JsonProperty("duration")]
        public string? Duration { get; set; } = null;

        /// <summary>
        /// The categories associated with this course
        /// </summary>
        [JsonProperty("categories")]
        public List<Category>? Categories { get; set; } = null;

        /// <summary>
        /// The skills associated with this course
        /// </summary>
        [JsonProperty("skills")]
        public List<Skills>? Skills { get; set; } = null;

        /// <summary>
        /// The name of the course provider
        /// </summary>
        [JsonProperty("provider")]
        public string? Provider { get; set; } = null;

        /// <summary>
        /// The authors of the course
        /// </summary>
        [JsonProperty("authors")]
        public List<AuthorModel>? Authors { get; set; } = null;

        /// <summary>
        /// The date on which the course was last updated.
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime? UpdatedAt { get; set; } = null;

        /// <summary>
        /// The date on which the course was created.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; } = null;
    }
}