//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The pay frequency of the job postings.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class EmploymentPayFrequencyValue : IEquatable<EmploymentPayFrequencyValue>
    {
        public static readonly EmploymentPayFrequencyValue Hourly = new EmploymentPayFrequencyValue("hourly");
        public static readonly EmploymentPayFrequencyValue Weekly = new EmploymentPayFrequencyValue("weekly");
        public static readonly EmploymentPayFrequencyValue BiWeekly = new EmploymentPayFrequencyValue("bi_weekly");
        public static readonly EmploymentPayFrequencyValue FourWeekly = new EmploymentPayFrequencyValue("four_weekly");
        public static readonly EmploymentPayFrequencyValue SemiMonthly = new EmploymentPayFrequencyValue("semi_monthly");
        public static readonly EmploymentPayFrequencyValue Monthly = new EmploymentPayFrequencyValue("monthly");
        public static readonly EmploymentPayFrequencyValue BiMonthly = new EmploymentPayFrequencyValue("bi_monthly");
        public static readonly EmploymentPayFrequencyValue Quarterly = new EmploymentPayFrequencyValue("quarterly");
        public static readonly EmploymentPayFrequencyValue SemiAnnually = new EmploymentPayFrequencyValue("semi_annually");
        public static readonly EmploymentPayFrequencyValue Yearly = new EmploymentPayFrequencyValue("yearly");
        public static readonly EmploymentPayFrequencyValue ThirteenMonthly = new EmploymentPayFrequencyValue("thirteen_monthly");
        public static readonly EmploymentPayFrequencyValue ProRata = new EmploymentPayFrequencyValue("pro_rata");
        public static readonly EmploymentPayFrequencyValue UnmappedValue = new EmploymentPayFrequencyValue("unmapped_value");
        public static readonly EmploymentPayFrequencyValue HalfYearly = new EmploymentPayFrequencyValue("half_yearly");
        public static readonly EmploymentPayFrequencyValue Daily = new EmploymentPayFrequencyValue("daily");

        private static readonly Dictionary <string, EmploymentPayFrequencyValue> _knownValues =
            new Dictionary <string, EmploymentPayFrequencyValue> ()
            {
                ["hourly"] = Hourly,
                ["weekly"] = Weekly,
                ["bi_weekly"] = BiWeekly,
                ["four_weekly"] = FourWeekly,
                ["semi_monthly"] = SemiMonthly,
                ["monthly"] = Monthly,
                ["bi_monthly"] = BiMonthly,
                ["quarterly"] = Quarterly,
                ["semi_annually"] = SemiAnnually,
                ["yearly"] = Yearly,
                ["thirteen_monthly"] = ThirteenMonthly,
                ["pro_rata"] = ProRata,
                ["unmapped_value"] = UnmappedValue,
                ["half_yearly"] = HalfYearly,
                ["daily"] = Daily
            };

        private static readonly ConcurrentDictionary<string, EmploymentPayFrequencyValue> _values =
            new ConcurrentDictionary<string, EmploymentPayFrequencyValue>(_knownValues);

        private EmploymentPayFrequencyValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static EmploymentPayFrequencyValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new EmploymentPayFrequencyValue(value));
        }

        public static implicit operator EmploymentPayFrequencyValue(string value) => Of(value);
        public static implicit operator string(EmploymentPayFrequencyValue employmentpayfrequencyvalue) => employmentpayfrequencyvalue.Value;

        public static EmploymentPayFrequencyValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as EmploymentPayFrequencyValue);

        public bool Equals(EmploymentPayFrequencyValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}