//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class EmploymentPayPeriodSourceValueUnionType
    {
        private EmploymentPayPeriodSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static EmploymentPayPeriodSourceValueUnionType Str { get { return new EmploymentPayPeriodSourceValueUnionType("str"); } }

        public static EmploymentPayPeriodSourceValueUnionType Number { get { return new EmploymentPayPeriodSourceValueUnionType("number"); } }

        public static EmploymentPayPeriodSourceValueUnionType Boolean { get { return new EmploymentPayPeriodSourceValueUnionType("boolean"); } }

        public static EmploymentPayPeriodSourceValueUnionType EmploymentSourceValuePayPeriod { get { return new EmploymentPayPeriodSourceValueUnionType("Employment_source_value_pay_period"); } }

        public static EmploymentPayPeriodSourceValueUnionType ArrayOfAny { get { return new EmploymentPayPeriodSourceValueUnionType("arrayOfAny"); } }

        public static EmploymentPayPeriodSourceValueUnionType Null { get { return new EmploymentPayPeriodSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(EmploymentPayPeriodSourceValueUnionType v) { return v.Value; }
        public static EmploymentPayPeriodSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "Employment_source_value_pay_period": return EmploymentSourceValuePayPeriod;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for EmploymentPayPeriodSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((EmploymentPayPeriodSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the pay period.
    /// </summary>
    [JsonConverter(typeof(EmploymentPayPeriodSourceValueUnion.EmploymentPayPeriodSourceValueUnionConverter))]
    public class EmploymentPayPeriodSourceValueUnion
    {
        public EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public EmploymentSourceValuePayPeriod? EmploymentSourceValuePayPeriod { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public EmploymentPayPeriodSourceValueUnionType Type { get; set; }
        public static EmploymentPayPeriodSourceValueUnion CreateStr(string str)
        {
            EmploymentPayPeriodSourceValueUnionType typ = EmploymentPayPeriodSourceValueUnionType.Str;

            EmploymentPayPeriodSourceValueUnion res = new EmploymentPayPeriodSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static EmploymentPayPeriodSourceValueUnion CreateNumber(double number)
        {
            EmploymentPayPeriodSourceValueUnionType typ = EmploymentPayPeriodSourceValueUnionType.Number;

            EmploymentPayPeriodSourceValueUnion res = new EmploymentPayPeriodSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static EmploymentPayPeriodSourceValueUnion CreateBoolean(bool boolean)
        {
            EmploymentPayPeriodSourceValueUnionType typ = EmploymentPayPeriodSourceValueUnionType.Boolean;

            EmploymentPayPeriodSourceValueUnion res = new EmploymentPayPeriodSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static EmploymentPayPeriodSourceValueUnion CreateEmploymentSourceValuePayPeriod(EmploymentSourceValuePayPeriod employmentSourceValuePayPeriod)
        {
            EmploymentPayPeriodSourceValueUnionType typ = EmploymentPayPeriodSourceValueUnionType.EmploymentSourceValuePayPeriod;

            EmploymentPayPeriodSourceValueUnion res = new EmploymentPayPeriodSourceValueUnion(typ);
            res.EmploymentSourceValuePayPeriod = employmentSourceValuePayPeriod;
            return res;
        }
        public static EmploymentPayPeriodSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            EmploymentPayPeriodSourceValueUnionType typ = EmploymentPayPeriodSourceValueUnionType.ArrayOfAny;

            EmploymentPayPeriodSourceValueUnion res = new EmploymentPayPeriodSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static EmploymentPayPeriodSourceValueUnion CreateNull()
        {
            EmploymentPayPeriodSourceValueUnionType typ = EmploymentPayPeriodSourceValueUnionType.Null;
            return new EmploymentPayPeriodSourceValueUnion(typ);
        }

        public class EmploymentPayPeriodSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(EmploymentPayPeriodSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.EmploymentSourceValuePayPeriod)
                    {
                        EmploymentSourceValuePayPeriod = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<EmploymentSourceValuePayPeriod>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(EmploymentSourceValuePayPeriod), new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.EmploymentSourceValuePayPeriod), "EmploymentSourceValuePayPeriod"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new EmploymentPayPeriodSourceValueUnion(EmploymentPayPeriodSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                EmploymentPayPeriodSourceValueUnion res = (EmploymentPayPeriodSourceValueUnion)value;
                if (EmploymentPayPeriodSourceValueUnionType.FromString(res.Type).Equals(EmploymentPayPeriodSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.EmploymentSourceValuePayPeriod != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.EmploymentSourceValuePayPeriod));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}