//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The type of the national identity number
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue : IEquatable<HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue>
    {
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ssn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ssn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Sin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("sin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Umcn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("umcn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pic = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pic");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ric = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ric");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Idnum = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("idnum");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nidnr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nidnr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pan = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pan");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Aadhaar = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("aadhaar");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Epic = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("epic");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ptn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ptn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Itin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("itin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Tin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("tin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Uprc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("uprc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pcode = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pcode");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ssi = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ssi");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cedula = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cedula");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Passport = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("passport");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Voterid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("voterid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ntin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ntin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Bn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("bn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Fnr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("fnr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Mva = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("mva");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue CivilId = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("civil_id");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cnic = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cnic");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nric = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nric");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Fin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("fin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Uen = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("uen");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Registrationnumber = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("registrationnumber");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nic = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nic");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Personnummer = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("personnummer");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ahv = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ahv");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Id = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("id");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Eid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("eid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Va = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("va");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nrt = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nrt");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nipt = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nipt");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cbu = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cbu");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cuit = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cuit");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Dni = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("dni");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Businessid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("businessid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Vnr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("vnr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Abn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("abn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Acn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("acn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Tfn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("tfn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Jmbg = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("jmbg");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Bis = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("bis");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Insz = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("insz");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Egn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("egn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pnf = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pnf");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Vat = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("vat");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cnpj = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cnpj");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Unp = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("unp");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Gst = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("gst");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pst = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pst");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Qst = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("qst");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ni = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ni");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Dic = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("dic");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Rc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("rc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Uid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("uid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Rut = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("rut");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Uscc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("uscc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cpf = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cpf");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cpj = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cpj");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Stnr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("stnr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Svnr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("svnr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ncf = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ncf");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Rnc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("rnc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nif = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nif");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ci = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ci");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ik = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ik");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Kmkr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("kmkr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Registrikood = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("registrikood");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Tn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("tn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ruc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ruc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nit = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nit");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Alv = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("alv");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Hetu = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("hetu");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ytunnus = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ytunnus");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Vn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("vn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Utr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("utr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nifp = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nifp");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Amka = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("amka");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Cui = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("cui");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nir = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nir");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Siren = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("siren");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Siret = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("siret");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Tva = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("tva");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Oib = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("oib");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Hkid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("hkid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Anum = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("anum");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Kennitala = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("kennitala");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Vsk = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("vsk");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Npwp = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("npwp");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pps = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pps");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Gstin = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("gstin");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Idnr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("idnr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Hr = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("hr");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Aic = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("aic");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Codicefiscale = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("codicefiscale");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Iva = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("iva");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Peid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("peid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Asmens = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("asmens");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pvm = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pvm");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ctps = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ctps");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Vrn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("vrn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Vtk = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("vtk");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Int = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("int");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Tk = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("tk");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pas = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pas");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Rne = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("rne");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Rg = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("rg");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nci = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nci");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Crnm = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("crnm");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pis = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pis");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Insee = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("insee");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Tax = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("tax");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Mpf = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("mpf");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Epfo = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("epfo");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Esi = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("esi");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Pran = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("pran");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Uan = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("uan");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Idk = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("idk");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Bsn = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("bsn");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Mid = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("mid");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Sss = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("sss");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nie = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nie");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Nss = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("nss");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Arc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("arc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Curp = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("curp");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Imss = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("imss");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Rfc = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("rfc");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Ein = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("ein");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Other = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("other");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Unknown = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("unknown");
        public static readonly HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue UnmappedValue = new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue("unmapped_value");

        private static readonly Dictionary <string, HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue> _knownValues =
            new Dictionary <string, HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue> ()
            {
                ["ssn"] = Ssn,
                ["nin"] = Nin,
                ["sin"] = Sin,
                ["nid"] = Nid,
                ["pin"] = Pin,
                ["pn"] = Pn,
                ["umcn"] = Umcn,
                ["pic"] = Pic,
                ["ric"] = Ric,
                ["idnum"] = Idnum,
                ["cid"] = Cid,
                ["nidnr"] = Nidnr,
                ["pan"] = Pan,
                ["aadhaar"] = Aadhaar,
                ["epic"] = Epic,
                ["ptn"] = Ptn,
                ["itin"] = Itin,
                ["tin"] = Tin,
                ["uprc"] = Uprc,
                ["pcode"] = Pcode,
                ["ssi"] = Ssi,
                ["cedula"] = Cedula,
                ["passport"] = Passport,
                ["voterid"] = Voterid,
                ["ntin"] = Ntin,
                ["bn"] = Bn,
                ["fnr"] = Fnr,
                ["mva"] = Mva,
                ["civil_id"] = CivilId,
                ["cnic"] = Cnic,
                ["nric"] = Nric,
                ["fin"] = Fin,
                ["uen"] = Uen,
                ["registrationnumber"] = Registrationnumber,
                ["nic"] = Nic,
                ["personnummer"] = Personnummer,
                ["ahv"] = Ahv,
                ["id"] = Id,
                ["eid"] = Eid,
                ["va"] = Va,
                ["pid"] = Pid,
                ["nrt"] = Nrt,
                ["nipt"] = Nipt,
                ["cbu"] = Cbu,
                ["cuit"] = Cuit,
                ["dni"] = Dni,
                ["businessid"] = Businessid,
                ["vnr"] = Vnr,
                ["abn"] = Abn,
                ["acn"] = Acn,
                ["tfn"] = Tfn,
                ["jmbg"] = Jmbg,
                ["bis"] = Bis,
                ["insz"] = Insz,
                ["nn"] = Nn,
                ["egn"] = Egn,
                ["pnf"] = Pnf,
                ["vat"] = Vat,
                ["cnpj"] = Cnpj,
                ["unp"] = Unp,
                ["gst"] = Gst,
                ["pst"] = Pst,
                ["qst"] = Qst,
                ["ni"] = Ni,
                ["dic"] = Dic,
                ["rc"] = Rc,
                ["uid"] = Uid,
                ["rut"] = Rut,
                ["uscc"] = Uscc,
                ["cpf"] = Cpf,
                ["cpj"] = Cpj,
                ["cr"] = Cr,
                ["stnr"] = Stnr,
                ["svnr"] = Svnr,
                ["ncf"] = Ncf,
                ["rnc"] = Rnc,
                ["nif"] = Nif,
                ["ci"] = Ci,
                ["ik"] = Ik,
                ["kmkr"] = Kmkr,
                ["registrikood"] = Registrikood,
                ["tn"] = Tn,
                ["ruc"] = Ruc,
                ["nit"] = Nit,
                ["alv"] = Alv,
                ["hetu"] = Hetu,
                ["ytunnus"] = Ytunnus,
                ["vn"] = Vn,
                ["utr"] = Utr,
                ["nifp"] = Nifp,
                ["amka"] = Amka,
                ["cui"] = Cui,
                ["nir"] = Nir,
                ["siren"] = Siren,
                ["siret"] = Siret,
                ["tva"] = Tva,
                ["oib"] = Oib,
                ["hkid"] = Hkid,
                ["anum"] = Anum,
                ["kennitala"] = Kennitala,
                ["vsk"] = Vsk,
                ["npwp"] = Npwp,
                ["pps"] = Pps,
                ["gstin"] = Gstin,
                ["idnr"] = Idnr,
                ["hr"] = Hr,
                ["aic"] = Aic,
                ["codicefiscale"] = Codicefiscale,
                ["iva"] = Iva,
                ["peid"] = Peid,
                ["asmens"] = Asmens,
                ["pvm"] = Pvm,
                ["ctps"] = Ctps,
                ["vrn"] = Vrn,
                ["vtk"] = Vtk,
                ["int"] = Int,
                ["tk"] = Tk,
                ["pas"] = Pas,
                ["rne"] = Rne,
                ["rg"] = Rg,
                ["nci"] = Nci,
                ["crnm"] = Crnm,
                ["pis"] = Pis,
                ["insee"] = Insee,
                ["tax"] = Tax,
                ["mpf"] = Mpf,
                ["epfo"] = Epfo,
                ["esi"] = Esi,
                ["pran"] = Pran,
                ["uan"] = Uan,
                ["idk"] = Idk,
                ["bsn"] = Bsn,
                ["mid"] = Mid,
                ["sss"] = Sss,
                ["nie"] = Nie,
                ["nss"] = Nss,
                ["arc"] = Arc,
                ["curp"] = Curp,
                ["imss"] = Imss,
                ["rfc"] = Rfc,
                ["ein"] = Ein,
                ["other"] = Other,
                ["unknown"] = Unknown,
                ["unmapped_value"] = UnmappedValue
            };

        private static readonly ConcurrentDictionary<string, HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue> _values =
            new ConcurrentDictionary<string, HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue>(_knownValues);

        private HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue(value));
        }

        public static implicit operator HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue(string value) => Of(value);
        public static implicit operator string(HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue hrisupdateemployeerequestdtonationalidentitynumbertypevalue) => hrisupdateemployeerequestdtonationalidentitynumbertypevalue.Value;

        public static HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue);

        public bool Equals(HrisUpdateEmployeeRequestDtoNationalIdentityNumberTypeValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}