//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type
    {
        private HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Str { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("str"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Number { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("number"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Boolean { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("boolean"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type HrisCreateEmployeeRequestDtoSourceValueEmploymentType1 { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("HrisCreateEmployeeRequestDto_source_value_employment_type_1"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type ArrayOfAny { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("arrayOfAny"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Null { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type v) { return v.Value; }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "HrisCreateEmployeeRequestDto_source_value_employment_type_1": return HrisCreateEmployeeRequestDtoSourceValueEmploymentType1;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the employment type.
    /// </summary>
    [JsonConverter(typeof(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1.HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Converter))]
    public class HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1
    {
        public HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public HrisCreateEmployeeRequestDtoSourceValueEmploymentType1? HrisCreateEmployeeRequestDtoSourceValueEmploymentType1 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Type { get; set; }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateStr(string str)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Str;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.Str = str;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateNumber(double number)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Number;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.Number = number;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateBoolean(bool boolean)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Boolean;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.Boolean = boolean;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateHrisCreateEmployeeRequestDtoSourceValueEmploymentType1(HrisCreateEmployeeRequestDtoSourceValueEmploymentType1 hrisCreateEmployeeRequestDtoSourceValueEmploymentType1)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.HrisCreateEmployeeRequestDtoSourceValueEmploymentType1;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.HrisCreateEmployeeRequestDtoSourceValueEmploymentType1 = hrisCreateEmployeeRequestDtoSourceValueEmploymentType1;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateArrayOfAny(List<object> arrayOfAny)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.ArrayOfAny;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateNull()
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Null;
            return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
        }

        public class HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.HrisCreateEmployeeRequestDtoSourceValueEmploymentType1)
                    {
                        HrisCreateEmployeeRequestDtoSourceValueEmploymentType1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<HrisCreateEmployeeRequestDtoSourceValueEmploymentType1>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(HrisCreateEmployeeRequestDtoSourceValueEmploymentType1), new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.HrisCreateEmployeeRequestDtoSourceValueEmploymentType1), "HrisCreateEmployeeRequestDtoSourceValueEmploymentType1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = (HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1)value;
                if (HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.FromString(res.Type).Equals(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.HrisCreateEmployeeRequestDtoSourceValueEmploymentType1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.HrisCreateEmployeeRequestDtoSourceValueEmploymentType1));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}