//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType
    {
        private HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType Str { get { return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType("str"); } }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType Number { get { return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType("number"); } }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType Boolean { get { return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType("boolean"); } }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType HrisUpdateEmployeeRequestDtoSourceValueGender { get { return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType("HrisUpdateEmployeeRequestDto_source_value_gender"); } }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType ArrayOfAny { get { return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType("arrayOfAny"); } }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType Null { get { return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType v) { return v.Value; }
        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "HrisUpdateEmployeeRequestDto_source_value_gender": return HrisUpdateEmployeeRequestDtoSourceValueGender;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(HrisUpdateEmployeeRequestDtoGenderSourceValueUnion.HrisUpdateEmployeeRequestDtoGenderSourceValueUnionConverter))]
    public class HrisUpdateEmployeeRequestDtoGenderSourceValueUnion
    {
        public HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public HrisUpdateEmployeeRequestDtoSourceValueGender? HrisUpdateEmployeeRequestDtoSourceValueGender { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType Type { get; set; }
        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnion CreateStr(string str)
        {
            HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType typ = HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Str;

            HrisUpdateEmployeeRequestDtoGenderSourceValueUnion res = new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnion CreateNumber(double number)
        {
            HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType typ = HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Number;

            HrisUpdateEmployeeRequestDtoGenderSourceValueUnion res = new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnion CreateBoolean(bool boolean)
        {
            HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType typ = HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Boolean;

            HrisUpdateEmployeeRequestDtoGenderSourceValueUnion res = new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnion CreateHrisUpdateEmployeeRequestDtoSourceValueGender(HrisUpdateEmployeeRequestDtoSourceValueGender hrisUpdateEmployeeRequestDtoSourceValueGender)
        {
            HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType typ = HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.HrisUpdateEmployeeRequestDtoSourceValueGender;

            HrisUpdateEmployeeRequestDtoGenderSourceValueUnion res = new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(typ);
            res.HrisUpdateEmployeeRequestDtoSourceValueGender = hrisUpdateEmployeeRequestDtoSourceValueGender;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType typ = HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.ArrayOfAny;

            HrisUpdateEmployeeRequestDtoGenderSourceValueUnion res = new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static HrisUpdateEmployeeRequestDtoGenderSourceValueUnion CreateNull()
        {
            HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType typ = HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Null;
            return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(typ);
        }

        public class HrisUpdateEmployeeRequestDtoGenderSourceValueUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(HrisUpdateEmployeeRequestDtoGenderSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.HrisUpdateEmployeeRequestDtoSourceValueGender)
                    {
                        HrisUpdateEmployeeRequestDtoSourceValueGender = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<HrisUpdateEmployeeRequestDtoSourceValueGender>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(HrisUpdateEmployeeRequestDtoSourceValueGender), new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.HrisUpdateEmployeeRequestDtoSourceValueGender), "HrisUpdateEmployeeRequestDtoSourceValueGender"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new HrisUpdateEmployeeRequestDtoGenderSourceValueUnion(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                HrisUpdateEmployeeRequestDtoGenderSourceValueUnion res = (HrisUpdateEmployeeRequestDtoGenderSourceValueUnion)value;
                if (HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.FromString(res.Type).Equals(HrisUpdateEmployeeRequestDtoGenderSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.HrisUpdateEmployeeRequestDtoSourceValueGender != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.HrisUpdateEmployeeRequestDtoSourceValueGender));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}