//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type
    {
        private HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type Str { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type("str"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type Number { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type("number"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type Boolean { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type("boolean"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type HrisCreateEmployeeRequestDtoSourceValueEmploymentType2 { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type("HrisCreateEmployeeRequestDto_source_value_employment_type_2"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type ArrayOfAny { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type("arrayOfAny"); } }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type Null { get { return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type v) { return v.Value; }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "HrisCreateEmployeeRequestDto_source_value_employment_type_2": return HrisCreateEmployeeRequestDtoSourceValueEmploymentType2;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2.HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Converter))]
    public class HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2
    {
        public HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public HrisCreateEmployeeRequestDtoSourceValueEmploymentType2? HrisCreateEmployeeRequestDtoSourceValueEmploymentType2 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type Type { get; set; }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 CreateStr(string str)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Str;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(typ);
            res.Str = str;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 CreateNumber(double number)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Number;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(typ);
            res.Number = number;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 CreateBoolean(bool boolean)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Boolean;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(typ);
            res.Boolean = boolean;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 CreateHrisCreateEmployeeRequestDtoSourceValueEmploymentType2(HrisCreateEmployeeRequestDtoSourceValueEmploymentType2 hrisCreateEmployeeRequestDtoSourceValueEmploymentType2)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.HrisCreateEmployeeRequestDtoSourceValueEmploymentType2;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(typ);
            res.HrisCreateEmployeeRequestDtoSourceValueEmploymentType2 = hrisCreateEmployeeRequestDtoSourceValueEmploymentType2;
            return res;
        }
        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 CreateArrayOfAny(List<object> arrayOfAny)
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.ArrayOfAny;

            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 res = new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 CreateNull()
        {
            HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type typ = HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Null;
            return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(typ);
        }

        public class HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Converter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.HrisCreateEmployeeRequestDtoSourceValueEmploymentType2)
                    {
                        HrisCreateEmployeeRequestDtoSourceValueEmploymentType2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<HrisCreateEmployeeRequestDtoSourceValueEmploymentType2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(HrisCreateEmployeeRequestDtoSourceValueEmploymentType2), new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.HrisCreateEmployeeRequestDtoSourceValueEmploymentType2), "HrisCreateEmployeeRequestDtoSourceValueEmploymentType2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2 res = (HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2)value;
                if (HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.FromString(res.Type).Equals(HrisCreateEmployeeRequestDtoEmploymentTypeSourceValueUnion2Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.HrisCreateEmployeeRequestDtoSourceValueEmploymentType2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.HrisCreateEmployeeRequestDtoSourceValueEmploymentType2));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}