//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    
    /// <summary>
    /// The ISO3166-2 sub division where the location is situated
    /// </summary>
    public class HrisUpdateEmployeeRequestDtoWorkLocationState
    {

        /// <summary>
        /// state (ISO3166-2 Sub Division Code) - value must be a valid enum value
        /// </summary>
        [JsonProperty("value")]
        public string? Value { get; set; } = null;

        [JsonProperty("source_value")]
        public HrisUpdateEmployeeRequestDtoWorkLocationStateSourceValueUnion? SourceValue { get; set; } = null;
    }
}