//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType
    {
        private HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType Str { get { return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType("str"); } }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType Number { get { return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType("number"); } }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType Boolean { get { return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType("boolean"); } }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType HrisUpdateEmploymentRequestDtoSourceValueEmploymentType { get { return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType("HrisUpdateEmploymentRequestDto_source_value_employment_type"); } }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType ArrayOfAny { get { return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType("arrayOfAny"); } }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType Null { get { return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType v) { return v.Value; }
        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "HrisUpdateEmploymentRequestDto_source_value_employment_type": return HrisUpdateEmploymentRequestDtoSourceValueEmploymentType;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the employment type.
    /// </summary>
    [JsonConverter(typeof(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion.HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionConverter))]
    public class HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion
    {
        public HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public HrisUpdateEmploymentRequestDtoSourceValueEmploymentType? HrisUpdateEmploymentRequestDtoSourceValueEmploymentType { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType Type { get; set; }
        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion CreateStr(string str)
        {
            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType typ = HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Str;

            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion res = new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion CreateNumber(double number)
        {
            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType typ = HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Number;

            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion res = new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion CreateBoolean(bool boolean)
        {
            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType typ = HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Boolean;

            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion res = new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion CreateHrisUpdateEmploymentRequestDtoSourceValueEmploymentType(HrisUpdateEmploymentRequestDtoSourceValueEmploymentType hrisUpdateEmploymentRequestDtoSourceValueEmploymentType)
        {
            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType typ = HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.HrisUpdateEmploymentRequestDtoSourceValueEmploymentType;

            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion res = new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(typ);
            res.HrisUpdateEmploymentRequestDtoSourceValueEmploymentType = hrisUpdateEmploymentRequestDtoSourceValueEmploymentType;
            return res;
        }
        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType typ = HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.ArrayOfAny;

            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion res = new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion CreateNull()
        {
            HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType typ = HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Null;
            return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(typ);
        }

        public class HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.HrisUpdateEmploymentRequestDtoSourceValueEmploymentType)
                    {
                        HrisUpdateEmploymentRequestDtoSourceValueEmploymentType = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<HrisUpdateEmploymentRequestDtoSourceValueEmploymentType>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(HrisUpdateEmploymentRequestDtoSourceValueEmploymentType), new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.HrisUpdateEmploymentRequestDtoSourceValueEmploymentType), "HrisUpdateEmploymentRequestDtoSourceValueEmploymentType"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion res = (HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnion)value;
                if (HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.FromString(res.Type).Equals(HrisUpdateEmploymentRequestDtoEmploymentTypeSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.HrisUpdateEmploymentRequestDtoSourceValueEmploymentType != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.HrisUpdateEmploymentRequestDtoSourceValueEmploymentType));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}