//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    [JsonConverter(typeof(OpenEnumConverter))]
    public class HrisCreateEmployeeRequestDtoEthnicityValue : IEquatable<HrisCreateEmployeeRequestDtoEthnicityValue>
    {
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue White = new HrisCreateEmployeeRequestDtoEthnicityValue("white");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue BlackOrAfricanAmerican = new HrisCreateEmployeeRequestDtoEthnicityValue("black_or_african_american");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue Asian = new HrisCreateEmployeeRequestDtoEthnicityValue("asian");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue HispanicOrLatino = new HrisCreateEmployeeRequestDtoEthnicityValue("hispanic_or_latino");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue AmericanIndianOrAlaskaNative = new HrisCreateEmployeeRequestDtoEthnicityValue("american_indian_or_alaska_native");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue NativeHawaiianOrPacificIslander = new HrisCreateEmployeeRequestDtoEthnicityValue("native_hawaiian_or_pacific_islander");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue TwoOrMoreRaces = new HrisCreateEmployeeRequestDtoEthnicityValue("two_or_more_races");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue NotDisclosed = new HrisCreateEmployeeRequestDtoEthnicityValue("not_disclosed");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue Other = new HrisCreateEmployeeRequestDtoEthnicityValue("other");
        public static readonly HrisCreateEmployeeRequestDtoEthnicityValue UnmappedValue = new HrisCreateEmployeeRequestDtoEthnicityValue("unmapped_value");

        private static readonly Dictionary <string, HrisCreateEmployeeRequestDtoEthnicityValue> _knownValues =
            new Dictionary <string, HrisCreateEmployeeRequestDtoEthnicityValue> ()
            {
                ["white"] = White,
                ["black_or_african_american"] = BlackOrAfricanAmerican,
                ["asian"] = Asian,
                ["hispanic_or_latino"] = HispanicOrLatino,
                ["american_indian_or_alaska_native"] = AmericanIndianOrAlaskaNative,
                ["native_hawaiian_or_pacific_islander"] = NativeHawaiianOrPacificIslander,
                ["two_or_more_races"] = TwoOrMoreRaces,
                ["not_disclosed"] = NotDisclosed,
                ["other"] = Other,
                ["unmapped_value"] = UnmappedValue
            };

        private static readonly ConcurrentDictionary<string, HrisCreateEmployeeRequestDtoEthnicityValue> _values =
            new ConcurrentDictionary<string, HrisCreateEmployeeRequestDtoEthnicityValue>(_knownValues);

        private HrisCreateEmployeeRequestDtoEthnicityValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static HrisCreateEmployeeRequestDtoEthnicityValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new HrisCreateEmployeeRequestDtoEthnicityValue(value));
        }

        public static implicit operator HrisCreateEmployeeRequestDtoEthnicityValue(string value) => Of(value);
        public static implicit operator string(HrisCreateEmployeeRequestDtoEthnicityValue hriscreateemployeerequestdtoethnicityvalue) => hriscreateemployeerequestdtoethnicityvalue.Value;

        public static HrisCreateEmployeeRequestDtoEthnicityValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as HrisCreateEmployeeRequestDtoEthnicityValue);

        public bool Equals(HrisCreateEmployeeRequestDtoEthnicityValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}