//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type
    {
        private HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Str { get { return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("str"); } }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Number { get { return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("number"); } }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Boolean { get { return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("boolean"); } }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1 { get { return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("HrisUpdateEmployeeRequestDto_source_value_employment_type_1"); } }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type ArrayOfAny { get { return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("arrayOfAny"); } }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Null { get { return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type v) { return v.Value; }
        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "HrisUpdateEmployeeRequestDto_source_value_employment_type_1": return HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the employment type.
    /// </summary>
    [JsonConverter(typeof(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1.HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Converter))]
    public class HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1
    {
        public HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1? HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type Type { get; set; }
        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateStr(string str)
        {
            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Str;

            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.Str = str;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateNumber(double number)
        {
            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Number;

            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.Number = number;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateBoolean(bool boolean)
        {
            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Boolean;

            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.Boolean = boolean;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateHrisUpdateEmployeeRequestDtoSourceValueEmploymentType1(HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1 hrisUpdateEmployeeRequestDtoSourceValueEmploymentType1)
        {
            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1;

            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1 = hrisUpdateEmployeeRequestDtoSourceValueEmploymentType1;
            return res;
        }
        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateArrayOfAny(List<object> arrayOfAny)
        {
            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.ArrayOfAny;

            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 CreateNull()
        {
            HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type typ = HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Null;
            return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(typ);
        }

        public class HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1)
                    {
                        HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1), new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1), "HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1 res = (HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1)value;
                if (HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.FromString(res.Type).Equals(HrisUpdateEmployeeRequestDtoEmploymentTypeSourceValueUnion1Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.HrisUpdateEmployeeRequestDtoSourceValueEmploymentType1));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}