//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class LinkedAccountStatus : IEquatable<LinkedAccountStatus>
    {
        public static readonly LinkedAccountStatus Active = new LinkedAccountStatus("active");
        public static readonly LinkedAccountStatus Inactive = new LinkedAccountStatus("inactive");
        public static readonly LinkedAccountStatus Suspended = new LinkedAccountStatus("suspended");
        public static readonly LinkedAccountStatus Archived = new LinkedAccountStatus("archived");
        public static readonly LinkedAccountStatus Expired = new LinkedAccountStatus("expired");
        public static readonly LinkedAccountStatus Error = new LinkedAccountStatus("error");

        private static readonly Dictionary <string, LinkedAccountStatus> _knownValues =
            new Dictionary <string, LinkedAccountStatus> ()
            {
                ["active"] = Active,
                ["inactive"] = Inactive,
                ["suspended"] = Suspended,
                ["archived"] = Archived,
                ["expired"] = Expired,
                ["error"] = Error
            };

        private static readonly ConcurrentDictionary<string, LinkedAccountStatus> _values =
            new ConcurrentDictionary<string, LinkedAccountStatus>(_knownValues);

        private LinkedAccountStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static LinkedAccountStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new LinkedAccountStatus(value));
        }

        public static implicit operator LinkedAccountStatus(string value) => Of(value);
        public static implicit operator string(LinkedAccountStatus linkedaccountstatus) => linkedaccountstatus.Value;

        public static LinkedAccountStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as LinkedAccountStatus);

        public bool Equals(LinkedAccountStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}