//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class LmsUpsertContentRequestDtoSourceValueUnionType
    {
        private LmsUpsertContentRequestDtoSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static LmsUpsertContentRequestDtoSourceValueUnionType Str { get { return new LmsUpsertContentRequestDtoSourceValueUnionType("str"); } }
        
        public static LmsUpsertContentRequestDtoSourceValueUnionType Number { get { return new LmsUpsertContentRequestDtoSourceValueUnionType("number"); } }
        
        public static LmsUpsertContentRequestDtoSourceValueUnionType Boolean { get { return new LmsUpsertContentRequestDtoSourceValueUnionType("boolean"); } }
        
        public static LmsUpsertContentRequestDtoSourceValueUnionType LmsUpsertContentRequestDtoSourceValue { get { return new LmsUpsertContentRequestDtoSourceValueUnionType("LmsUpsertContentRequestDto_source_value"); } }
        
        public static LmsUpsertContentRequestDtoSourceValueUnionType ArrayOfAny { get { return new LmsUpsertContentRequestDtoSourceValueUnionType("arrayOfAny"); } }
        
        public static LmsUpsertContentRequestDtoSourceValueUnionType Null { get { return new LmsUpsertContentRequestDtoSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(LmsUpsertContentRequestDtoSourceValueUnionType v) { return v.Value; }
        public static LmsUpsertContentRequestDtoSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "LmsUpsertContentRequestDto_source_value": return LmsUpsertContentRequestDtoSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for LmsUpsertContentRequestDtoSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((LmsUpsertContentRequestDtoSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(LmsUpsertContentRequestDtoSourceValueUnion.LmsUpsertContentRequestDtoSourceValueUnionConverter))]
    public class LmsUpsertContentRequestDtoSourceValueUnion {
        public LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public LmsUpsertContentRequestDtoSourceValue? LmsUpsertContentRequestDtoSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public LmsUpsertContentRequestDtoSourceValueUnionType Type { get; set; }


        public static LmsUpsertContentRequestDtoSourceValueUnion CreateStr(string str) {
            LmsUpsertContentRequestDtoSourceValueUnionType typ = LmsUpsertContentRequestDtoSourceValueUnionType.Str;

            LmsUpsertContentRequestDtoSourceValueUnion res = new LmsUpsertContentRequestDtoSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static LmsUpsertContentRequestDtoSourceValueUnion CreateNumber(double number) {
            LmsUpsertContentRequestDtoSourceValueUnionType typ = LmsUpsertContentRequestDtoSourceValueUnionType.Number;

            LmsUpsertContentRequestDtoSourceValueUnion res = new LmsUpsertContentRequestDtoSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static LmsUpsertContentRequestDtoSourceValueUnion CreateBoolean(bool boolean) {
            LmsUpsertContentRequestDtoSourceValueUnionType typ = LmsUpsertContentRequestDtoSourceValueUnionType.Boolean;

            LmsUpsertContentRequestDtoSourceValueUnion res = new LmsUpsertContentRequestDtoSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static LmsUpsertContentRequestDtoSourceValueUnion CreateLmsUpsertContentRequestDtoSourceValue(LmsUpsertContentRequestDtoSourceValue lmsUpsertContentRequestDtoSourceValue) {
            LmsUpsertContentRequestDtoSourceValueUnionType typ = LmsUpsertContentRequestDtoSourceValueUnionType.LmsUpsertContentRequestDtoSourceValue;

            LmsUpsertContentRequestDtoSourceValueUnion res = new LmsUpsertContentRequestDtoSourceValueUnion(typ);
            res.LmsUpsertContentRequestDtoSourceValue = lmsUpsertContentRequestDtoSourceValue;
            return res;
        }

        public static LmsUpsertContentRequestDtoSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            LmsUpsertContentRequestDtoSourceValueUnionType typ = LmsUpsertContentRequestDtoSourceValueUnionType.ArrayOfAny;

            LmsUpsertContentRequestDtoSourceValueUnion res = new LmsUpsertContentRequestDtoSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static LmsUpsertContentRequestDtoSourceValueUnion CreateNull() {
            LmsUpsertContentRequestDtoSourceValueUnionType typ = LmsUpsertContentRequestDtoSourceValueUnionType.Null;
            return new LmsUpsertContentRequestDtoSourceValueUnion(typ);
        }

        public class LmsUpsertContentRequestDtoSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(LmsUpsertContentRequestDtoSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.LmsUpsertContentRequestDtoSourceValue)
                    {
                        LmsUpsertContentRequestDtoSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<LmsUpsertContentRequestDtoSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(LmsUpsertContentRequestDtoSourceValue), new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.LmsUpsertContentRequestDtoSourceValue), "LmsUpsertContentRequestDtoSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new LmsUpsertContentRequestDtoSourceValueUnion(LmsUpsertContentRequestDtoSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                LmsUpsertContentRequestDtoSourceValueUnion res = (LmsUpsertContentRequestDtoSourceValueUnion)value;
                if (LmsUpsertContentRequestDtoSourceValueUnionType.FromString(res.Type).Equals(LmsUpsertContentRequestDtoSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.LmsUpsertContentRequestDtoSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.LmsUpsertContentRequestDtoSourceValue));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}