//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class LmsUpsertContentRequestDtoActiveUnionType
    {
        private LmsUpsertContentRequestDtoActiveUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static LmsUpsertContentRequestDtoActiveUnionType Boolean { get { return new LmsUpsertContentRequestDtoActiveUnionType("boolean"); } }
        
        public static LmsUpsertContentRequestDtoActiveUnionType LmsUpsertContentRequestDtoActiveEnum { get { return new LmsUpsertContentRequestDtoActiveUnionType("LmsUpsertContentRequestDto_active_enum"); } }
        
        public static LmsUpsertContentRequestDtoActiveUnionType Null { get { return new LmsUpsertContentRequestDtoActiveUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(LmsUpsertContentRequestDtoActiveUnionType v) { return v.Value; }
        public static LmsUpsertContentRequestDtoActiveUnionType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "LmsUpsertContentRequestDto_active_enum": return LmsUpsertContentRequestDtoActiveEnum;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for LmsUpsertContentRequestDtoActiveUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((LmsUpsertContentRequestDtoActiveUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Whether the content is active and available for users.
    /// </summary>
    [JsonConverter(typeof(LmsUpsertContentRequestDtoActiveUnion.LmsUpsertContentRequestDtoActiveUnionConverter))]
    public class LmsUpsertContentRequestDtoActiveUnion {
        public LmsUpsertContentRequestDtoActiveUnion(LmsUpsertContentRequestDtoActiveUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public LmsUpsertContentRequestDtoActiveEnum? LmsUpsertContentRequestDtoActiveEnum { get; set; }

        public LmsUpsertContentRequestDtoActiveUnionType Type { get; set; }


        public static LmsUpsertContentRequestDtoActiveUnion CreateBoolean(bool boolean) {
            LmsUpsertContentRequestDtoActiveUnionType typ = LmsUpsertContentRequestDtoActiveUnionType.Boolean;

            LmsUpsertContentRequestDtoActiveUnion res = new LmsUpsertContentRequestDtoActiveUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static LmsUpsertContentRequestDtoActiveUnion CreateLmsUpsertContentRequestDtoActiveEnum(LmsUpsertContentRequestDtoActiveEnum lmsUpsertContentRequestDtoActiveEnum) {
            LmsUpsertContentRequestDtoActiveUnionType typ = LmsUpsertContentRequestDtoActiveUnionType.LmsUpsertContentRequestDtoActiveEnum;

            LmsUpsertContentRequestDtoActiveUnion res = new LmsUpsertContentRequestDtoActiveUnion(typ);
            res.LmsUpsertContentRequestDtoActiveEnum = lmsUpsertContentRequestDtoActiveEnum;
            return res;
        }

        public static LmsUpsertContentRequestDtoActiveUnion CreateNull() {
            LmsUpsertContentRequestDtoActiveUnionType typ = LmsUpsertContentRequestDtoActiveUnionType.Null;
            return new LmsUpsertContentRequestDtoActiveUnion(typ);
        }

        public class LmsUpsertContentRequestDtoActiveUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(LmsUpsertContentRequestDtoActiveUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new LmsUpsertContentRequestDtoActiveUnion(LmsUpsertContentRequestDtoActiveUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new LmsUpsertContentRequestDtoActiveUnion(LmsUpsertContentRequestDtoActiveUnionType.LmsUpsertContentRequestDtoActiveEnum)
                    {
                        LmsUpsertContentRequestDtoActiveEnum = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<LmsUpsertContentRequestDtoActiveEnum>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(LmsUpsertContentRequestDtoActiveEnum), new LmsUpsertContentRequestDtoActiveUnion(LmsUpsertContentRequestDtoActiveUnionType.LmsUpsertContentRequestDtoActiveEnum), "LmsUpsertContentRequestDtoActiveEnum"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                LmsUpsertContentRequestDtoActiveUnion res = (LmsUpsertContentRequestDtoActiveUnion)value;
                if (LmsUpsertContentRequestDtoActiveUnionType.FromString(res.Type).Equals(LmsUpsertContentRequestDtoActiveUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.LmsUpsertContentRequestDtoActiveEnum != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.LmsUpsertContentRequestDtoActiveEnum));
                    return;
                }

            }

        }

    }
}