//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The type of this status
    /// </summary>
    public class TicketingTicketUpdateRequestDtoType
    {

        /// <summary>
        /// The type of this status
        /// </summary>
        [JsonProperty("value")]
        public TicketingTicketUpdateRequestDtoStatusValue? Value { get; set; } = null;

        /// <summary>
        /// The source value of this status type
        /// </summary>
        [JsonProperty("source_value")]
        public TicketingTicketUpdateRequestDtoStatusSourceValueUnion? SourceValue { get; set; } = null;
    }
}