//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class TicketingTicketStatusSourceValueUnionType
    {
        private TicketingTicketStatusSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static TicketingTicketStatusSourceValueUnionType Str { get { return new TicketingTicketStatusSourceValueUnionType("str"); } }
        
        public static TicketingTicketStatusSourceValueUnionType Number { get { return new TicketingTicketStatusSourceValueUnionType("number"); } }
        
        public static TicketingTicketStatusSourceValueUnionType Boolean { get { return new TicketingTicketStatusSourceValueUnionType("boolean"); } }
        
        public static TicketingTicketStatusSourceValueUnionType TicketingTicketStatusSourceValue { get { return new TicketingTicketStatusSourceValueUnionType("TicketingTicketStatus_source_value"); } }
        
        public static TicketingTicketStatusSourceValueUnionType ArrayOfAny { get { return new TicketingTicketStatusSourceValueUnionType("arrayOfAny"); } }
        
        public static TicketingTicketStatusSourceValueUnionType Null { get { return new TicketingTicketStatusSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TicketingTicketStatusSourceValueUnionType v) { return v.Value; }
        public static TicketingTicketStatusSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "TicketingTicketStatus_source_value": return TicketingTicketStatusSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for TicketingTicketStatusSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TicketingTicketStatusSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of this status type
    /// </summary>
    [JsonConverter(typeof(TicketingTicketStatusSourceValueUnion.TicketingTicketStatusSourceValueUnionConverter))]
    public class TicketingTicketStatusSourceValueUnion {
        public TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public TicketingTicketStatusSourceValue? TicketingTicketStatusSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public TicketingTicketStatusSourceValueUnionType Type { get; set; }


        public static TicketingTicketStatusSourceValueUnion CreateStr(string str) {
            TicketingTicketStatusSourceValueUnionType typ = TicketingTicketStatusSourceValueUnionType.Str;

            TicketingTicketStatusSourceValueUnion res = new TicketingTicketStatusSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static TicketingTicketStatusSourceValueUnion CreateNumber(double number) {
            TicketingTicketStatusSourceValueUnionType typ = TicketingTicketStatusSourceValueUnionType.Number;

            TicketingTicketStatusSourceValueUnion res = new TicketingTicketStatusSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static TicketingTicketStatusSourceValueUnion CreateBoolean(bool boolean) {
            TicketingTicketStatusSourceValueUnionType typ = TicketingTicketStatusSourceValueUnionType.Boolean;

            TicketingTicketStatusSourceValueUnion res = new TicketingTicketStatusSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static TicketingTicketStatusSourceValueUnion CreateTicketingTicketStatusSourceValue(TicketingTicketStatusSourceValue ticketingTicketStatusSourceValue) {
            TicketingTicketStatusSourceValueUnionType typ = TicketingTicketStatusSourceValueUnionType.TicketingTicketStatusSourceValue;

            TicketingTicketStatusSourceValueUnion res = new TicketingTicketStatusSourceValueUnion(typ);
            res.TicketingTicketStatusSourceValue = ticketingTicketStatusSourceValue;
            return res;
        }

        public static TicketingTicketStatusSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            TicketingTicketStatusSourceValueUnionType typ = TicketingTicketStatusSourceValueUnionType.ArrayOfAny;

            TicketingTicketStatusSourceValueUnion res = new TicketingTicketStatusSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static TicketingTicketStatusSourceValueUnion CreateNull() {
            TicketingTicketStatusSourceValueUnionType typ = TicketingTicketStatusSourceValueUnionType.Null;
            return new TicketingTicketStatusSourceValueUnion(typ);
        }

        public class TicketingTicketStatusSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(TicketingTicketStatusSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.TicketingTicketStatusSourceValue)
                    {
                        TicketingTicketStatusSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TicketingTicketStatusSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TicketingTicketStatusSourceValue), new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.TicketingTicketStatusSourceValue), "TicketingTicketStatusSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new TicketingTicketStatusSourceValueUnion(TicketingTicketStatusSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                TicketingTicketStatusSourceValueUnion res = (TicketingTicketStatusSourceValueUnion)value;
                if (TicketingTicketStatusSourceValueUnionType.FromString(res.Type).Equals(TicketingTicketStatusSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.TicketingTicketStatusSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TicketingTicketStatusSourceValue));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}