//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TicketingTicketUpdateRequestDtoStatusSourceValueUnionType
    {
        private TicketingTicketUpdateRequestDtoStatusSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType Str { get { return new TicketingTicketUpdateRequestDtoStatusSourceValueUnionType("str"); } }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType Number { get { return new TicketingTicketUpdateRequestDtoStatusSourceValueUnionType("number"); } }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType Boolean { get { return new TicketingTicketUpdateRequestDtoStatusSourceValueUnionType("boolean"); } }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType TicketingTicketUpdateRequestDtoSourceValueStatus { get { return new TicketingTicketUpdateRequestDtoStatusSourceValueUnionType("TicketingTicketUpdateRequestDto_source_value_status"); } }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType ArrayOfAny { get { return new TicketingTicketUpdateRequestDtoStatusSourceValueUnionType("arrayOfAny"); } }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType Null { get { return new TicketingTicketUpdateRequestDtoStatusSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType v) { return v.Value; }
        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "TicketingTicketUpdateRequestDto_source_value_status": return TicketingTicketUpdateRequestDtoSourceValueStatus;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for TicketingTicketUpdateRequestDtoStatusSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TicketingTicketUpdateRequestDtoStatusSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of this status type
    /// </summary>
    [JsonConverter(typeof(TicketingTicketUpdateRequestDtoStatusSourceValueUnion.TicketingTicketUpdateRequestDtoStatusSourceValueUnionConverter))]
    public class TicketingTicketUpdateRequestDtoStatusSourceValueUnion
    {
        public TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public TicketingTicketUpdateRequestDtoSourceValueStatus? TicketingTicketUpdateRequestDtoSourceValueStatus { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public TicketingTicketUpdateRequestDtoStatusSourceValueUnionType Type { get; set; }
        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnion CreateStr(string str)
        {
            TicketingTicketUpdateRequestDtoStatusSourceValueUnionType typ = TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Str;

            TicketingTicketUpdateRequestDtoStatusSourceValueUnion res = new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(typ);
            res.Str = str;
            return res;
        }
        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnion CreateNumber(double number)
        {
            TicketingTicketUpdateRequestDtoStatusSourceValueUnionType typ = TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Number;

            TicketingTicketUpdateRequestDtoStatusSourceValueUnion res = new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(typ);
            res.Number = number;
            return res;
        }
        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnion CreateBoolean(bool boolean)
        {
            TicketingTicketUpdateRequestDtoStatusSourceValueUnionType typ = TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Boolean;

            TicketingTicketUpdateRequestDtoStatusSourceValueUnion res = new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }
        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnion CreateTicketingTicketUpdateRequestDtoSourceValueStatus(TicketingTicketUpdateRequestDtoSourceValueStatus ticketingTicketUpdateRequestDtoSourceValueStatus)
        {
            TicketingTicketUpdateRequestDtoStatusSourceValueUnionType typ = TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.TicketingTicketUpdateRequestDtoSourceValueStatus;

            TicketingTicketUpdateRequestDtoStatusSourceValueUnion res = new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(typ);
            res.TicketingTicketUpdateRequestDtoSourceValueStatus = ticketingTicketUpdateRequestDtoSourceValueStatus;
            return res;
        }
        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny)
        {
            TicketingTicketUpdateRequestDtoStatusSourceValueUnionType typ = TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.ArrayOfAny;

            TicketingTicketUpdateRequestDtoStatusSourceValueUnion res = new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static TicketingTicketUpdateRequestDtoStatusSourceValueUnion CreateNull()
        {
            TicketingTicketUpdateRequestDtoStatusSourceValueUnionType typ = TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Null;
            return new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(typ);
        }

        public class TicketingTicketUpdateRequestDtoStatusSourceValueUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(TicketingTicketUpdateRequestDtoStatusSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.TicketingTicketUpdateRequestDtoSourceValueStatus)
                    {
                        TicketingTicketUpdateRequestDtoSourceValueStatus = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TicketingTicketUpdateRequestDtoSourceValueStatus>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TicketingTicketUpdateRequestDtoSourceValueStatus), new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.TicketingTicketUpdateRequestDtoSourceValueStatus), "TicketingTicketUpdateRequestDtoSourceValueStatus"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new TicketingTicketUpdateRequestDtoStatusSourceValueUnion(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                TicketingTicketUpdateRequestDtoStatusSourceValueUnion res = (TicketingTicketUpdateRequestDtoStatusSourceValueUnion)value;
                if (TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.FromString(res.Type).Equals(TicketingTicketUpdateRequestDtoStatusSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.TicketingTicketUpdateRequestDtoSourceValueStatus != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TicketingTicketUpdateRequestDtoSourceValueStatus));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }

        }

    }
}