//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The unified value for the duration unit. If the provider does not specify this unit, the value will be set to unknown
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class TimeOffPoliciesDurationUnitValue : IEquatable<TimeOffPoliciesDurationUnitValue>
    {
        public static readonly TimeOffPoliciesDurationUnitValue Minutes = new TimeOffPoliciesDurationUnitValue("minutes");
        public static readonly TimeOffPoliciesDurationUnitValue Hours = new TimeOffPoliciesDurationUnitValue("hours");
        public static readonly TimeOffPoliciesDurationUnitValue Days = new TimeOffPoliciesDurationUnitValue("days");
        public static readonly TimeOffPoliciesDurationUnitValue Weeks = new TimeOffPoliciesDurationUnitValue("weeks");
        public static readonly TimeOffPoliciesDurationUnitValue Months = new TimeOffPoliciesDurationUnitValue("months");
        public static readonly TimeOffPoliciesDurationUnitValue Years = new TimeOffPoliciesDurationUnitValue("years");
        public static readonly TimeOffPoliciesDurationUnitValue Unknown = new TimeOffPoliciesDurationUnitValue("unknown");
        public static readonly TimeOffPoliciesDurationUnitValue UnmappedValue = new TimeOffPoliciesDurationUnitValue("unmapped_value");

        private static readonly Dictionary <string, TimeOffPoliciesDurationUnitValue> _knownValues =
            new Dictionary <string, TimeOffPoliciesDurationUnitValue> ()
            {
                ["minutes"] = Minutes,
                ["hours"] = Hours,
                ["days"] = Days,
                ["weeks"] = Weeks,
                ["months"] = Months,
                ["years"] = Years,
                ["unknown"] = Unknown,
                ["unmapped_value"] = UnmappedValue
            };

        private static readonly ConcurrentDictionary<string, TimeOffPoliciesDurationUnitValue> _values =
            new ConcurrentDictionary<string, TimeOffPoliciesDurationUnitValue>(_knownValues);

        private TimeOffPoliciesDurationUnitValue(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static TimeOffPoliciesDurationUnitValue Of(string value)
        {
            return _values.GetOrAdd(value, _ => new TimeOffPoliciesDurationUnitValue(value));
        }

        public static implicit operator TimeOffPoliciesDurationUnitValue(string value) => Of(value);
        public static implicit operator string(TimeOffPoliciesDurationUnitValue timeoffpoliciesdurationunitvalue) => timeoffpoliciesdurationunitvalue.Value;

        public static TimeOffPoliciesDurationUnitValue[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as TimeOffPoliciesDurationUnitValue);

        public bool Equals(TimeOffPoliciesDurationUnitValue? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}