//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOneHQ.Client.Models.Components;
    using StackOneHQ.Client.Utils;
    
    /// <summary>
    /// The category of the file
    /// </summary>
    public class WorkEligibilityCategory
    {

        /// <summary>
        /// The category of the file
        /// </summary>
        [JsonProperty("value")]
        public string? Value { get; set; } = null;

        [JsonProperty("source_value")]
        public WorkEligibilityCategorySourceValueUnion? SourceValue { get; set; } = null;
    }
}