//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Requests
{
    using StackOneHQ.Client.Utils;
    using System;
    
    /// <summary>
    /// LMS Courses Filter
    /// </summary>
    public class LmsListCoursesFilter
    {

        /// <summary>
        /// Use a string with a date to only select results updated after that given date
        /// </summary>
        [SpeakeasyMetadata("queryParam:name=updated_after")]
        public DateTime? UpdatedAfter { get; set; } = null;

        /// <summary>
        /// Filter to select courses by external_reference
        /// </summary>
        [SpeakeasyMetadata("queryParam:name=external_reference")]
        public string? ExternalReference { get; set; } = null;
    }
}