//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOneHQ.Client.Models.Requests
{
    using StackOneHQ.Client.Models.Requests;
    using StackOneHQ.Client.Utils;
    using System.Collections.Generic;

    public class StackoneListActionsMetaRequest
    {
        /// <summary>
        /// The number of results per page (default value is 25).
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")]
        public string? PageSize { get; set; } = null;

        /// <summary>
        /// The unified cursor.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=next")]
        public string? Next { get; set; } = null;

        /// <summary>
        /// The relation to group the results by.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=group_by")]
        public string? GroupBy { get; set; } = "connector";

        /// <summary>
        /// Actions Metadata filters.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=deepObject,explode=true,name=filter")]
        public StackoneListActionsMetaFilter? Filter { get; set; } = null;

        /// <summary>
        /// Additional data to include in the response.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include")]
        public List<StackoneListActionsMetaInclude>? Include { get; set; } = null;

        /// <summary>
        /// Text search across provider names, action labels, and action descriptions.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=search")]
        public string? Search { get; set; } = null;

        /// <summary>
        /// Data to exclude from the response.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=exclude")]
        public List<Exclude>? Exclude { get; set; } = null;
    }
}