//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System.Collections.Generic;
    
    public class CustomFieldDefinition
    {

        /// <summary>
        /// Unique identifier
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Provider&apos;s unique identifier
        /// </summary>
        [JsonProperty("remote_id")]
        public string? RemoteId { get; set; } = null;

        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// The type of the custom field.
        /// </summary>
        [JsonProperty("type")]
        public CustomFieldDefinitionType? Type { get; set; } = null;

        /// <summary>
        /// An array of possible options for the custom field.
        /// </summary>
        [JsonProperty("options")]
        public List<CustomFieldOption>? Options { get; set; } = null;
    }
}