//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System.Collections.Generic;
    
    public class EmploymentResult
    {

        [JsonProperty("data")]
        public Employment Data { get; set; } = default!;

        [JsonProperty("raw")]
        public List<RawResponse>? Raw { get; set; } = null;
    }
}