//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System;
    using System.Collections.Generic;
    
    public class HrisCreateEmploymentRequestDto
    {

        /// <summary>
        /// Custom Unified Fields configured in your StackOne project
        /// </summary>
        [JsonProperty("unified_custom_fields")]
        public Dictionary<string, object>? UnifiedCustomFields { get; set; } = null;

        /// <summary>
        /// The job title of the employee
        /// </summary>
        [JsonProperty("job_title")]
        public string? JobTitle { get; set; } = null;

        /// <summary>
        /// The pay rate for the employee
        /// </summary>
        [JsonProperty("pay_rate")]
        public string? PayRate { get; set; } = null;

        /// <summary>
        /// The pay period
        /// </summary>
        [JsonProperty("pay_period")]
        public HrisCreateEmploymentRequestDtoPayPeriod? PayPeriod { get; set; } = null;

        /// <summary>
        /// The pay frequency
        /// </summary>
        [JsonProperty("pay_frequency")]
        public HrisCreateEmploymentRequestDtoPayFrequency? PayFrequency { get; set; } = null;

        /// <summary>
        /// The currency used for pay
        /// </summary>
        [JsonProperty("pay_currency")]
        public string? PayCurrency { get; set; } = null;

        /// <summary>
        /// The effective date of the employment contract
        /// </summary>
        [JsonProperty("effective_date")]
        public DateTime? EffectiveDate { get; set; } = null;

        /// <summary>
        /// The end date of employment
        /// </summary>
        [JsonProperty("end_date")]
        public DateTime? EndDate { get; set; } = null;

        /// <summary>
        /// Represents the employee’s position within the organizational hierarchy.
        /// </summary>
        [JsonProperty("grade")]
        public HrisCreateEmploymentRequestDtoGrade? Grade { get; set; } = null;

        /// <summary>
        /// The type of employment (e.g., contractor, permanent)
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("employment_type")]
        public HrisCreateEmploymentRequestDtoEmploymentType? EmploymentType { get; set; } = null;

        /// <summary>
        /// The employment work schedule type (e.g., full-time, part-time)
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("employment_contract_type")]
        public HrisCreateEmploymentRequestDtoEmploymentContractType? EmploymentContractType { get; set; } = null;

        [JsonProperty("work_time")]
        public HrisCreateEmploymentRequestDtoWorkTime? WorkTime { get; set; } = null;

        /// <summary>
        /// The payroll code of the employee
        /// </summary>
        [JsonProperty("payroll_code")]
        public string? PayrollCode { get; set; } = null;

        /// <summary>
        /// The employee job id
        /// </summary>
        [JsonProperty("job_id")]
        public string? JobId { get; set; } = null;

        /// <summary>
        /// Value to pass through to the provider
        /// </summary>
        [JsonProperty("passthrough")]
        public Dictionary<string, object>? Passthrough { get; set; } = null;
    }
}