//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// The employee work location
    /// </summary>
    public class HrisUpdateEmployeeRequestDtoWorkLocation
    {

        /// <summary>
        /// Unique identifier
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// The name of the location
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        /// <summary>
        /// The phone number of the location
        /// </summary>
        [JsonProperty("phone_number")]
        public string? PhoneNumber { get; set; } = null;

        /// <summary>
        /// The first line of the address
        /// </summary>
        [JsonProperty("street_1")]
        public string? Street1 { get; set; } = null;

        /// <summary>
        /// The second line of the address
        /// </summary>
        [JsonProperty("street_2")]
        public string? Street2 { get; set; } = null;

        /// <summary>
        /// The city where the location is situated
        /// </summary>
        [JsonProperty("city")]
        public string? City { get; set; } = null;

        /// <summary>
        /// The ZIP code/Postal code of the location
        /// </summary>
        [JsonProperty("zip_code")]
        public string? ZipCode { get; set; } = null;

        /// <summary>
        /// The country code
        /// </summary>
        [JsonProperty("country")]
        public HrisUpdateEmployeeRequestDtoWorkLocationCountry? Country { get; set; } = null;

        /// <summary>
        /// Value to pass through to the provider
        /// </summary>
        [JsonProperty("passthrough")]
        public Dictionary<string, object>? Passthrough { get; set; } = null;

        /// <summary>
        /// The ISO3166-2 sub division where the location is situated
        /// </summary>
        [JsonProperty("state")]
        public HrisUpdateEmployeeRequestDtoWorkLocationState? State { get; set; } = null;
    }
}