//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The file format of the file
    /// </summary>
    public class HrisDocumentsUploadRequestDtoFileFormat
    {

        /// <summary>
        /// The file format of the file, expressed as a file extension
        /// </summary>
        [JsonProperty("value")]
        public HrisDocumentsUploadRequestDtoFileFormatValue? Value { get; set; } = null;

        [JsonProperty("source_value")]
        public HrisDocumentsUploadRequestDtoFileFormatSourceValueUnion? SourceValue { get; set; } = null;
    }
}