//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class JobPostingContentSectionSourceValueUnionType
    {
        private JobPostingContentSectionSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static JobPostingContentSectionSourceValueUnionType Str { get { return new JobPostingContentSectionSourceValueUnionType("str"); } }
        
        public static JobPostingContentSectionSourceValueUnionType Number { get { return new JobPostingContentSectionSourceValueUnionType("number"); } }
        
        public static JobPostingContentSectionSourceValueUnionType Boolean { get { return new JobPostingContentSectionSourceValueUnionType("boolean"); } }
        
        public static JobPostingContentSectionSourceValueUnionType JobPostingContentSectionSourceValue { get { return new JobPostingContentSectionSourceValueUnionType("JobPostingContentSection_source_value"); } }
        
        public static JobPostingContentSectionSourceValueUnionType ArrayOfAny { get { return new JobPostingContentSectionSourceValueUnionType("arrayOfAny"); } }
        
        public static JobPostingContentSectionSourceValueUnionType Null { get { return new JobPostingContentSectionSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(JobPostingContentSectionSourceValueUnionType v) { return v.Value; }
        public static JobPostingContentSectionSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "JobPostingContentSection_source_value": return JobPostingContentSectionSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for JobPostingContentSectionSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((JobPostingContentSectionSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The source value of the description type.
    /// </summary>
    [JsonConverter(typeof(JobPostingContentSectionSourceValueUnion.JobPostingContentSectionSourceValueUnionConverter))]
    public class JobPostingContentSectionSourceValueUnion {
        public JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public JobPostingContentSectionSourceValue? JobPostingContentSectionSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public JobPostingContentSectionSourceValueUnionType Type { get; set; }


        public static JobPostingContentSectionSourceValueUnion CreateStr(string str) {
            JobPostingContentSectionSourceValueUnionType typ = JobPostingContentSectionSourceValueUnionType.Str;

            JobPostingContentSectionSourceValueUnion res = new JobPostingContentSectionSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static JobPostingContentSectionSourceValueUnion CreateNumber(double number) {
            JobPostingContentSectionSourceValueUnionType typ = JobPostingContentSectionSourceValueUnionType.Number;

            JobPostingContentSectionSourceValueUnion res = new JobPostingContentSectionSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static JobPostingContentSectionSourceValueUnion CreateBoolean(bool boolean) {
            JobPostingContentSectionSourceValueUnionType typ = JobPostingContentSectionSourceValueUnionType.Boolean;

            JobPostingContentSectionSourceValueUnion res = new JobPostingContentSectionSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static JobPostingContentSectionSourceValueUnion CreateJobPostingContentSectionSourceValue(JobPostingContentSectionSourceValue jobPostingContentSectionSourceValue) {
            JobPostingContentSectionSourceValueUnionType typ = JobPostingContentSectionSourceValueUnionType.JobPostingContentSectionSourceValue;

            JobPostingContentSectionSourceValueUnion res = new JobPostingContentSectionSourceValueUnion(typ);
            res.JobPostingContentSectionSourceValue = jobPostingContentSectionSourceValue;
            return res;
        }

        public static JobPostingContentSectionSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            JobPostingContentSectionSourceValueUnionType typ = JobPostingContentSectionSourceValueUnionType.ArrayOfAny;

            JobPostingContentSectionSourceValueUnion res = new JobPostingContentSectionSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static JobPostingContentSectionSourceValueUnion CreateNull() {
            JobPostingContentSectionSourceValueUnionType typ = JobPostingContentSectionSourceValueUnionType.Null;
            return new JobPostingContentSectionSourceValueUnion(typ);
        }

        public class JobPostingContentSectionSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(JobPostingContentSectionSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.JobPostingContentSectionSourceValue)
                    {
                        JobPostingContentSectionSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<JobPostingContentSectionSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(JobPostingContentSectionSourceValue), new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.JobPostingContentSectionSourceValue), "JobPostingContentSectionSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new JobPostingContentSectionSourceValueUnion(JobPostingContentSectionSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                JobPostingContentSectionSourceValueUnion res = (JobPostingContentSectionSourceValueUnion)value;
                if (JobPostingContentSectionSourceValueUnionType.FromString(res.Type).Equals(JobPostingContentSectionSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.JobPostingContentSectionSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.JobPostingContentSectionSourceValue));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}