//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using StackOne.Client.Models.Components;
    using StackOne.Client.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class LocalizationModelSourceValueUnionType
    {
        private LocalizationModelSourceValueUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static LocalizationModelSourceValueUnionType Str { get { return new LocalizationModelSourceValueUnionType("str"); } }
        
        public static LocalizationModelSourceValueUnionType Number { get { return new LocalizationModelSourceValueUnionType("number"); } }
        
        public static LocalizationModelSourceValueUnionType Boolean { get { return new LocalizationModelSourceValueUnionType("boolean"); } }
        
        public static LocalizationModelSourceValueUnionType LocalizationModelSourceValue { get { return new LocalizationModelSourceValueUnionType("LocalizationModel_source_value"); } }
        
        public static LocalizationModelSourceValueUnionType ArrayOfAny { get { return new LocalizationModelSourceValueUnionType("arrayOfAny"); } }
        
        public static LocalizationModelSourceValueUnionType Null { get { return new LocalizationModelSourceValueUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(LocalizationModelSourceValueUnionType v) { return v.Value; }
        public static LocalizationModelSourceValueUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "LocalizationModel_source_value": return LocalizationModelSourceValue;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for LocalizationModelSourceValueUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((LocalizationModelSourceValueUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(LocalizationModelSourceValueUnion.LocalizationModelSourceValueUnionConverter))]
    public class LocalizationModelSourceValueUnion {
        public LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public LocalizationModelSourceValue? LocalizationModelSourceValue { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public LocalizationModelSourceValueUnionType Type { get; set; }


        public static LocalizationModelSourceValueUnion CreateStr(string str) {
            LocalizationModelSourceValueUnionType typ = LocalizationModelSourceValueUnionType.Str;

            LocalizationModelSourceValueUnion res = new LocalizationModelSourceValueUnion(typ);
            res.Str = str;
            return res;
        }

        public static LocalizationModelSourceValueUnion CreateNumber(double number) {
            LocalizationModelSourceValueUnionType typ = LocalizationModelSourceValueUnionType.Number;

            LocalizationModelSourceValueUnion res = new LocalizationModelSourceValueUnion(typ);
            res.Number = number;
            return res;
        }

        public static LocalizationModelSourceValueUnion CreateBoolean(bool boolean) {
            LocalizationModelSourceValueUnionType typ = LocalizationModelSourceValueUnionType.Boolean;

            LocalizationModelSourceValueUnion res = new LocalizationModelSourceValueUnion(typ);
            res.Boolean = boolean;
            return res;
        }

        public static LocalizationModelSourceValueUnion CreateLocalizationModelSourceValue(LocalizationModelSourceValue localizationModelSourceValue) {
            LocalizationModelSourceValueUnionType typ = LocalizationModelSourceValueUnionType.LocalizationModelSourceValue;

            LocalizationModelSourceValueUnion res = new LocalizationModelSourceValueUnion(typ);
            res.LocalizationModelSourceValue = localizationModelSourceValue;
            return res;
        }

        public static LocalizationModelSourceValueUnion CreateArrayOfAny(List<object> arrayOfAny) {
            LocalizationModelSourceValueUnionType typ = LocalizationModelSourceValueUnionType.ArrayOfAny;

            LocalizationModelSourceValueUnion res = new LocalizationModelSourceValueUnion(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static LocalizationModelSourceValueUnion CreateNull() {
            LocalizationModelSourceValueUnionType typ = LocalizationModelSourceValueUnionType.Null;
            return new LocalizationModelSourceValueUnion(typ);
        }

        public class LocalizationModelSourceValueUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(LocalizationModelSourceValueUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.LocalizationModelSourceValue)
                    {
                        LocalizationModelSourceValue = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<LocalizationModelSourceValue>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(LocalizationModelSourceValue), new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.LocalizationModelSourceValue), "LocalizationModelSourceValue"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new LocalizationModelSourceValueUnion(LocalizationModelSourceValueUnionType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                LocalizationModelSourceValueUnion res = (LocalizationModelSourceValueUnion)value;
                if (LocalizationModelSourceValueUnionType.FromString(res.Type).Equals(LocalizationModelSourceValueUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.LocalizationModelSourceValue != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.LocalizationModelSourceValue));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }

            }

        }

    }
}