//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace StackOne.Client.Models.Components
{
    using Newtonsoft.Json;
    using StackOne.Client.Utils;
    using System;
    
    public class TaskCommentApiModel
    {

        /// <summary>
        /// The Employee ID of the author of the comment
        /// </summary>
        [JsonProperty("author_employee_id")]
        public string? AuthorEmployeeId { get; set; } = null;

        /// <summary>
        /// The text of the comment
        /// </summary>
        [JsonProperty("comment")]
        public string? Comment { get; set; } = null;

        /// <summary>
        /// The creation date of this comment
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; } = null;
    }
}